Repository mockingbirdnest/Principia, pull requests merged in 2018-12, with the labels that each got.

#1997 Simplify the setting of the plotting frame through the interface
  ksp_plugin/interface.cpp
  ksp_plugin/interface_renderer.cpp
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  serialization/journal.proto
Labels: LGTM, journal-incompatible

#2002 Change the generator to support custom marshalers
  ksp_plugin/interface.cpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
Labels: LGTM

#2000 Fix the Trappist-1 blueprint
  astronomy/trappist_numerics_blueprint.cfg
  astronomy/trappist_numerics_blueprint.proto.txt
  mathematica/mathematica_body.hpp
Labels: LGTM

#2001 Adjust some test tolerances for Linux
  astronomy/geodesy_test.cpp
  physics/ephemeris_test.cpp
  physics/geopotential_test.cpp
Labels: LGTM

#2006 Next release is Εὔδοξος
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#2007 Fix references to null geopotential
  ksp_plugin_adapter/class_marshalers.cs
  ksp_plugin_adapter/config_node_parsers.cs
Labels: TBR

#2008 Upgrade to Visual Studio 2017 15.9.3 preview 1
  astronomy/trappist_dynamics_test.cpp
  base/base.vcxproj
  base/base32768_body.hpp
  base/base32768_test.cpp
  base/bundle.hpp
  base/bundle_test.cpp
  base/not_null_test.cpp
  ksp_plugin_test/manœuvre_test.cpp
  principia.props
Labels: LGTM

#2010 Serialization of the Fine integrator
  integrators/integrators_body.hpp
  integrators/methods.hpp
  serialization/integrators.proto
Labels: LGTM

#2011 New C++ redistributable runtime for 15.9
  ksp_plugin_adapter/loader.cs
Labels: LGTM

#2017 Do not try ordering NaN
  physics/geopotential_body.hpp
Labels: LGTM

#2013 Distinguish AdaptiveStepParameters and GeneralizedAdaptiveStepParameters in name only
  ksp_plugin/flight_plan.cpp
  ksp_plugin/flight_plan.hpp
  ksp_plugin/integrators.cpp
  ksp_plugin/integrators.hpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/vessel_test.cpp
  physics/ephemeris.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#2020 Change the ephemeris to factor out the adaptive step integration
  ksp_physics/ksp_physics_lib.hpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/integrators.cpp
  ksp_plugin/manœuvre.hpp
  ksp_plugin/manœuvre_body.hpp
  ksp_plugin_test/flight_plan_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
Labels: LGTM

#2022 Remove unused initial_direction from C#
  journal/profiles.hpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/flight_plan.hpp
  ksp_plugin/interface.hpp
  ksp_plugin/interface_body.hpp
  ksp_plugin/interface_flight_plan.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/flight_planner.cs
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/interface_flight_plan_test.cpp
  ksp_plugin_test/mock_flight_plan.hpp
  ksp_plugin_test/plugin_integration_test.cpp
  ksp_plugin_test/simple_plugin.proto.bin
  ksp_plugin_test/simple_plugin.proto.hex
  serialization/journal.proto
  serialization/ksp_plugin.proto
Labels: LGTM

#2023 Make it build on mac
  base/bundle.cpp
  integrators/integrators_body.hpp
  physics/ephemeris_body.hpp
Labels: LGTM

#2024 Actually implement IAU 29 resolution B3
  astronomy/trappist_dynamics_test.cpp
  astronomy/trappist_gravity_model.proto.txt
  benchmarks/dynamic_frame.cpp
  physics/apsides_test.cpp
  physics/ephemeris_test.cpp
  quantities/astronomy.hpp
  quantities/elementary_functions_test.cpp
  quantities/parser_body.hpp
  quantities/quantities_test.cpp
Labels: LGTM

#2027 Add an Encoder interface and derive the encoders/decoders from that interface
  base/base.vcxproj
  base/base.vcxproj.filters
  base/base32768.hpp
  base/base32768_body.hpp
  base/base32768_test.cpp
  base/encoder.hpp
  base/hexadecimal.hpp
  base/hexadecimal_body.hpp
  base/hexadecimal_test.cpp
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  benchmarks/encoder.cpp
  benchmarks/hexadecimal.cpp
  journal/player.cpp
  journal/recorder.cpp
  ksp_plugin/interface.cpp
  ksp_plugin/part.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  mathematica/retrobop_dynamical_stability.cpp
  testing_utilities/serialization_body.hpp
Labels: LGTM

#2028 An encoder for base 64
  base/base.vcxproj
  base/base.vcxproj.filters
  base/base64.hpp
  base/base64_body.hpp
  base/base64_test.cpp
  base/encoder.hpp
  base/hexadecimal.hpp
  benchmarks/encoder.cpp
Labels: LGTM

#2030 15.9.4 has the same bugs as 15.9.3
  base/base32768_body.hpp
  base/base32768_test.cpp
  base/not_null_test.cpp
  benchmarks/encoder.cpp
  ksp_plugin_test/manœuvre_test.cpp
Labels: LGTM

#2033 A mechanism for asynchronous deletion of objects
  astronomy/trappist_dynamics_test.cpp
  base/base.vcxproj
  base/base.vcxproj.filters
  base/graveyard.hpp
  base/graveyard_body.hpp
Labels: LGTM

#2003 New parameters for Trappist optimization
  astronomy/trappist_dynamics_test.cpp
Labels: LGTM

#2034 Remove the implicit constructor for AccuracyParameters
  astronomy/geodesy_test.cpp
  astronomy/ksp_resonance_test.cpp
  astronomy/ksp_system_test.cpp
  astronomy/lunar_eclipse_test.cpp
  astronomy/mercury_perihelion_test.cpp
  astronomy/solar_system_dynamics_test.cpp
  astronomy/trappist_dynamics_test.cpp
  astronomy/молния_orbit_test.cpp
  benchmarks/dynamic_frame.cpp
  benchmarks/ephemeris.cpp
  benchmarks/planetarium_plot_methods.cpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/pile_up_test.cpp
  mathematica/local_error_analysis.cpp
  mathematica/retrobop_dynamical_stability.cpp
  physics/apsides_test.cpp
  physics/barycentric_rotating_dynamic_frame_test.cpp
  physics/body_centred_body_direction_dynamic_frame_test.cpp
  physics/body_centred_non_rotating_dynamic_frame_test.cpp
  physics/body_surface_dynamic_frame_test.cpp
  physics/body_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
  physics/solar_system_test.cpp
Labels: LGTM

#2035 Population bundle and separate logging
  astronomy/trappist_dynamics_test.cpp
Labels: LGTM

#2036 Ignore AccessViolationException in the coverage analyser
  coverage_analyser/coverage_analyser.cs
Labels: LGTM

#2037 More DEМCMC generations
  astronomy/trappist_dynamics_test.cpp
Labels: LGTM

#2039 Fix the coverage path
  coverage_analyser/coverage_analyser.csproj
Labels: LGTM

#2032 Selenopotential to degree and order 50
  astronomy/geodesy_test.cpp
  astronomy/sol_gravity_model.proto.txt
  mathematica/associated_legendre_function.wl
  numerics/legendre_normalization_factor.mathematica.h
  numerics/max_abs_normalized_associated_legendre_function.mathematica.h
  numerics/max_abs_normalized_associated_legendre_functions_test.cc
  physics/geopotential_body.hpp
  physics/oblate_body.hpp
Labels: LGTM

#2042 An allocator based on arenas
  base/arena_allocator.hpp
  base/arena_allocator_body.hpp
  base/arena_allocator_test.cpp
  base/base.vcxproj
  base/base.vcxproj.filters
Labels: LGTM

#2044 Change optimization parameters
  astronomy/trappist_dynamics_test.cpp
Labels: LGTM

#2046 Fix the test to be able to read gipfeli saves
  ksp_plugin_test/interface_test.cpp
Labels: LGTM

#2047 Trappist optimization results
  astronomy/trappist_dynamics_test.cpp
  astronomy/trappist_gravity_model.cfg
  astronomy/trappist_gravity_model_slippist1.cfg
  astronomy/trappist_initial_state_jd_2457000_000000000.cfg
  astronomy/trappist_initial_state_jd_2457000_000000000.proto.txt
  astronomy/trappist_numerics_blueprint.cfg
  astronomy/trappist_numerics_blueprint.proto.txt
  quantities/parser_body.hpp
  tools/generate_configuration.cpp
  tools/generate_kopernicus.cpp
Labels: LGTM
