Repository mockingbirdnest/Principia, pull requests merged in 2021-12, with the labels that each got.

#3221 A factory for an accelerated trajectory
  testing_utilities/discrete_trajectory_factories.hpp
  testing_utilities/discrete_trajectory_factories_body.hpp
  testing_utilities/discrete_trajectory_factories_test.cpp
Labels: LGTM

#3222 Make sure that the number of dense points is correctly maintained by serialization and ForgetAfter
  physics/discrete_trajectory_segment_body.hpp
  physics/discrete_trajectory_segment_test.cpp
Labels: LGTM

#3224 Next release is Hardy
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3223 Only write the number of dense points if downsampling is enabled
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_segment_body.hpp
  serialization/physics.proto
Labels: LGTM

#3228 Pick up the Hamilton hotfix
  ksp_plugin_adapter/localization_extensions.cs
  ksp_plugin_adapter/lru_cache.cs
Labels: LGTM

#3225 Use new-style DiscreteTrajectory in Entwurf
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/vessel_test.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_iterator_body.hpp
  physics/discrete_trajectory_segment_body.hpp
  physics/ephemeris_test.cpp
  serialization/physics.proto
Labels: LGTM

#3231 Start the flight plan at the end of the backstory, not at the end of the history
  ksp_plugin/vessel.cpp
Labels: LGTM

#3232 Make progress on segments of size 2
  physics/discrete_trajectory_iterator_body.hpp
Labels: LGTM

#3233 Fix a bug when rebasing the flight plan
  ksp_plugin/vessel.cpp
Labels: LGTM

#3234 Compute time spans in Double, not Int, to avoid overflows
  ksp_plugin_adapter/time_span.cs
Labels: LGTM

#3237 Track the backstory when checkpointing
  ksp_plugin/vessel.cpp
Labels: LGTM

#3238 Some support for nested placeholders
  documentation/Setup.md
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization_extensions.cs
Labels: LGTM, localization

#3241 A consistency check for merging trajectory segments
  physics/discrete_trajectory_segment_body.hpp
Labels: LGTM

#3242 Fix t_min for a trajectory starting with empty segments
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3240 Move Plugin I/O utilities to their own file
  ksp_plugin_test/benchmark.cpp
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/plugin_io.cpp
  ksp_plugin_test/plugin_io.hpp
Labels: LGTM

#3243 Fix size for a trajectory starting with empty segments
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3246 Add Checkpoint::checkpoint_at_or_after
  physics/checkpointer.hpp
  physics/checkpointer_body.hpp
  physics/checkpointer_test.cpp
Labels: LGTM

#3248 Proper management of the time-to-segment map when merging trajectories with 1-point segments
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3247 Bypass stock aerodynamics outside the atmosphere
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#3251 Initialize the styles more lazily
  ksp_plugin_adapter/style.cs
Labels: LGTM

#3253 Do not ship Assembly-CSharp-firstpass
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
Labels: LGTM

#3250 Ungarble unsupported languages somewhat
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/localization_extensions.cs
Labels: LGTM

#3254 Hamilton compatibility
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/saves/3244.proto.b64
  physics/discrete_trajectory_segment_body.hpp
Labels: LGTM

#3252 Some localization issues
  ksp_plugin_adapter/localization/celestial_strings.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
Labels: LGTM

#3256 Instant DebugString consistent with operator<<
  geometry/instant_output.cpp
  geometry/named_quantities.hpp
Labels: LGTM

#3249 Orient the camera in CelestialSphere, not World
  ksp_plugin/renderer.cpp
  ksp_plugin/renderer.hpp
Labels: LGTM

#3257 NaN-aware consistency check
  physics/discrete_trajectory_body.hpp
Labels: LGTM

#3259 Fix a bug where ForgetAfter was creating orphaned 1-point segments
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3260 Merge was not processing the segments of the target after the end of the source
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3258 Russian translations
  documentation/bibliography.bib
  documentation/bibliography.pdf
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization/ru.cfg
  ksp_plugin_adapter/localization_extensions.cs
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM, localization

#3261 Russian celestial strings
  ksp_plugin_adapter/localization/celestial_strings.cfg
Labels: LGTM

#3262 Reanimation of vessel trajectories
  ksp_plugin/interface_external.cpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/plugin_integration_test.cpp
  ksp_plugin_test/reanimation test.proto.b64
  ksp_plugin_test/vessel_test.cpp
  physics/ephemeris_body.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3263 Add dependency on plugin_io
  Makefile
Labels: LGTM

#3264 Make it link
  Makefile
Labels: TBR

#3265 Do not look for Plugin IO in testing_utilities
  Makefile
Labels: TBR
