Repository mockingbirdnest/Principia, pull requests merged in 2021-03, with the labels that each got.

#2900 Use system allocator for containers on macOS (bypassing Unity's allocator)
  Makefile
  base/macos_allocator_replacement.hpp
  base/macos_allocator_replacement_test.cpp
  base/malloc_allocator.hpp
  base/malloc_allocator_test.cpp
  mathematica/error_analysis_test.cpp
  physics/discrete_trajectory.hpp
Labels: LGTM

#2907 Fix some lint
  base/base.vcxproj
  base/base.vcxproj.filters
  base/macos_allocator_replacement.hpp
  base/macos_allocator_replacement_test.cpp
Labels: LGTM

#2905 Some fixes to our LaTeX package
  documentation/Celledoni.pdf
  documentation/Celledoni.tex
  documentation/Fukushima.pdf
  documentation/Fukushima.tex
  documentation/Geopotential.pdf
  documentation/Geopotential.tex
  documentation/J2 coefficient.pdf
  documentation/J2 coefficient.tex
  documentation/Legendre.pdf
  documentation/Legendre.tex
  documentation/Perspective hiding.pdf
  documentation/Perspective hiding.tex
  documentation/bibliography.pdf
  documentation/semtex.sty
Labels: LGTM

#2904 Additions to the bibliography
  astronomy/mercury_perihelion_test.cpp
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM

#2914 Bibliography cleanups
  documentation/Celledoni.pdf
  documentation/Celledoni.tex
  documentation/Fukushima.pdf
  documentation/Fukushima.tex
  documentation/Geopotential.pdf
  documentation/Geopotential.tex
  documentation/J2 coefficient.pdf
  documentation/Perspective hiding.pdf
  documentation/basestyle.cls
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/bibliography.tex
Labels: LGTM

#2915 Sort and format the the bibliography
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/format_bibliography.ps1
Labels: LGTM

#2916 Italicize Latin locutions
  documentation/Celledoni.pdf
  documentation/Celledoni.tex
  documentation/Fukushima.pdf
  documentation/Geopotential.pdf
  documentation/Geopotential.tex
  documentation/J2 coefficient.pdf
  documentation/ODEs and Runge-Kutta integrators.tex
  documentation/Perspective hiding.pdf
  documentation/Perspective hiding.tex
  documentation/basestyle.cls
Labels: LGTM, documentation

#2917 Don’t (partially⁉︎) abbreviate SIAM J. Sci. Comput. in [CFSZ08], it is named in extenso elsewhere.
  documentation/Celledoni.pdf
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM, documentation

#2918 Fix Composition methods.tex
  documentation/Composition methods.pdf
  documentation/Composition methods.tex
  documentation/Fukushima.pdf
  documentation/Geopotential.pdf
  documentation/J2 coefficient.pdf
  documentation/Legendre.pdf
  documentation/Perspective hiding.pdf
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/rebuild_all_documents.ps1
  documentation/semtex.sty
Labels: TBR, documentation

#2920 Reproducible TeX builds
  documentation/Celledoni.pdf
  documentation/Composition methods.pdf
  documentation/Fukushima.pdf
  documentation/Geopotential.pdf
  documentation/J2 coefficient.pdf
  documentation/Legendre.pdf
  documentation/Perspective hiding.pdf
  documentation/bibliography.pdf
  documentation/rebuild_all_documents.ps1
Labels: LGTM, documentation

#2921 Prefer double quotes
  documentation/Celledoni.pdf
  documentation/Composition methods.pdf
  documentation/Fukushima.pdf
  documentation/basestyle.cls
  documentation/bibliography.pdf
Labels: LGTM, documentation

#2923 Uniformize layout
  documentation/Celledoni.pdf
  documentation/Celledoni.tex
  documentation/Composition methods.pdf
  documentation/Composition methods.tex
  documentation/Fukushima.pdf
  documentation/Fukushima.tex
  documentation/Geopotential.pdf
  documentation/Geopotential.tex
  documentation/J2 coefficient.pdf
  documentation/J2 coefficient.tex
  documentation/Legendre.pdf
  documentation/Legendre.tex
  documentation/Perspective hiding.pdf
  documentation/Perspective hiding.tex
  documentation/basestyle.cls
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/bibliography.tex
Labels: LGTM, documentation

#2925 Remove stray StringRiffle in fornberg.wl
  mathematica/fornberg.wl
Labels: LGTM

#2926 Smarter override of version check
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#2924 Document the Cohen-Hubbard-Oesterwinter formula
  documentation/Cohen Hubbard Oesterwinter.pdf
  documentation/Cohen Hubbard Oesterwinter.tex
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/semtex.sty
  integrators/cohen_hubbard_oesterwinter.hpp
Labels: LGTM

#2927 Fix naming of const variables in C#
  ksp_plugin_adapter/burn_editor.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/main_window.cs
  ksp_plugin_adapter/window_renderer.cs
Labels: LGTM

#2929 Update the .wl file to reflect the documentation
  documentation/Cohen Hubbard Oesterwinter.pdf
  documentation/Cohen Hubbard Oesterwinter.tex
  mathematica/cohen_hubbard_oesterwinter.wl
Labels: LGTM

#2930 Remove ForgetBefore from most places
  ksp_plugin/flight_plan.cpp
  ksp_plugin/flight_plan.hpp
  ksp_plugin/interface.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/mock_vessel.hpp
  ksp_plugin_test/plugin_test.cpp
  mathematica/retrobop_dynamical_stability.cpp
  physics/checkpointer.hpp
  physics/checkpointer_body.hpp
  physics/checkpointer_test.cpp
  physics/continuous_trajectory.hpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
  physics/mock_ephemeris.hpp
  serialization/journal.proto
Labels: LGTM, journal-incompatible
