Repository mockingbirdnest/Principia, pull requests merged in 2021-06, with the labels that each got.

#3020 No FMA with clang
  Makefile
  numerics/fma.hpp
  numerics/fma_body.hpp
  numerics/fma_test.cpp
Labels: LGTM

#3021 Missed a test with an FMA
  quantities/elementary_functions_test.cpp
Labels: LGTM

#3022 FMA for geometry
  geometry/grassmann.hpp
  geometry/grassmann_body.hpp
  geometry/grassmann_test.cpp
  geometry/point.hpp
  geometry/point_body.hpp
  geometry/point_test.cpp
  geometry/r3_element.hpp
  geometry/r3_element_body.hpp
  numerics/fma_test.cpp
  quantities/elementary_functions_test.cpp
Labels: LGTM

#3024 Solution filter files for our two languages
  Principia C#.slnf
  Principia C++.slnf
Labels: TBR

#3025 Next release is Grossmann
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3026 Fix the release script
  make_principia_release.ps1
Labels: LGTM

#3027 Adjust glog paths
  google_glog.props
  principia.props
  rebuild_all_solutions.ps1
Labels: LGTM

#3023 FMA in polynomial evaluation
  astronomy/orbital_elements_test.cpp
  numerics/frequency_analysis_test.cpp
  numerics/newhall_test.cpp
  numerics/poisson_series_test.cpp
  numerics/polynomial_evaluators.hpp
  numerics/polynomial_evaluators_body.hpp
  numerics/root_finders_test.cpp
  physics/body_centred_non_rotating_dynamic_frame_test.cpp
  physics/continuous_trajectory_test.cpp
  physics/ephemeris_test.cpp
Labels: LGTM, performance

#3028 Fix the build
  numerics/polynomial_evaluators.hpp
Labels: TBR

#3029 Fix the build more
  numerics/polynomial_evaluators_body.hpp
Labels: TBR

#3030 No exported namespace
  numerics/polynomial_evaluators.hpp
  numerics/polynomial_evaluators_body.hpp
Labels: LGTM

#3031 Some cleanups in class Vessel
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
Labels: LGTM

#3032 Add a predicate to check if a vessel is in a state that allows collapsing its trajectory
  ksp_plugin/pile_up.cpp
  ksp_plugin/pile_up.hpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/vessel_test.cpp
Labels: LGTM

#3036 Fix the manifest for the new name of glog
  ksp_plugin/principia.manifest
Labels: LGTM

#2973 Documentation for a correctly-rounded cube root
  documentation/Cohen Hubbard Oesterwinter.pdf
  documentation/Geopotential.pdf
  documentation/basestyle.cls
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/cbrt.pdf
  documentation/cbrt.tex
  documentation/cbrt_latency_misrounding.pdf
  documentation/cbrt_ξ_error.pdf
  documentation/semtex.sty
Labels: LGTM, documentation
