Repository mockingbirdnest/Principia, pull requests merged in 2021-05, with the labels that each got.

#2968 Support for restarting a RecurringThread
  base/recurring_thread.hpp
  base/recurring_thread_body.hpp
Labels: LGTM

#2969 More functions in the Checkpointer
  physics/checkpointer.hpp
  physics/checkpointer_body.hpp
  physics/checkpointer_test.cpp
Labels: LGTM

#2970 Documentation changes to ContinuousTrajectory
  physics/continuous_trajectory.hpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
Labels: LGTM

#2971 Only append the barycentre of the parts if it is after the end of the trajectory
  journal/player.cpp
  journal/player_test.cpp
  journal/profiles.cpp
  ksp_plugin/vessel.cpp
Labels: LGTM

#2972 A mechanism to only reanimate the parts of the celestial histories that are actually displayed
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  physics/checkpointer_body.hpp
  physics/checkpointer_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
Labels: LGTM

#2976 Close planned orbit analyser if there is no flight plan
  ksp_plugin_adapter/orbit_analyser.cs
Labels: LGTM

#2977 Next release is Gröbner
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#2980 Properly handle stopping in Prolong
  ksp_plugin/orbit_analyser.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/mock_ephemeris.hpp
Labels: LGTM

#2983 If a vessel only contains unfaithful parts, make it unmanageable
  journal/player_test.cpp
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#2981 Optimizations for DiscreteTrajectory
  benchmarks/discrete_trajectory.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  physics/forkable_test.cpp
Labels: LGTM

#2985 Fix the Lov22 entry in the bibliography
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM

#2986 An optional branch parameter
  make_principia_release.ps1
Labels: LGTM

#2987 A packed vessel is not unfaithful
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#2988 Add a trait to detect a vector space and use it in Pair
  geometry/geometry.vcxproj
  geometry/geometry.vcxproj.filters
  geometry/pair.hpp
  geometry/pair_body.hpp
  geometry/pair_test.cpp
  geometry/traits.hpp
  geometry/traits_test.cpp
Labels: LGTM

#2989 Rewrite PolynomialInMonomialBasis to avoid specializations
  numerics/polynomial.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_test.cpp
  serialization/numerics.proto
Labels: LGTM

#2991 Document the catch-up process
  documentation/Catching Up.md
Labels: LGTM, documentation

#2992 Improved catching-up documentation
  Principia.sln
  documentation/Catching Up.md
Labels: LGTM, documentation

#2993 Fix link errors related to absl on macOS
  Makefile
Labels: LGTM

#2994 Upgrade to VS 16.10.0 preview 4
  base/not_null_test.cpp
  coverage_analyser/coverage_analyser.csproj
  find_msbuild.ps1
  numerics/double_precision_body.hpp
  numerics/double_precision_test.cpp
  numerics/unbounded_arrays_body.hpp
  principia.props
Labels: LGTM

#2995 Use polynomial origin in EllipticK
  numerics/elliptic_integrals.cpp
Labels: LGTM

#2996 Additive operators for converting vector-valued and affine valued polynomials
  numerics/polynomial.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_test.cpp
Labels: LGTM

#2998 Support for affine-valued polynomials in Newhall
  numerics/newhall.hpp
  numerics/newhall_body.hpp
  numerics/newhall_test.cpp
Labels: LGTM

#2999 Use affine-valued polynomials for continuous trajectories
  numerics/newhall_body.hpp
  physics/continuous_trajectory.hpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
Labels: LGTM

#2990 CPUID
  base/base.vcxproj
  base/base.vcxproj.filters
  base/cpuid.cpp
  base/cpuid.hpp
  base/cpuid_test.cpp
  base/not_null_test.cpp
Labels: LGTM

#3000 Remove an ancient work-around for a VS2015 bug
  ksp_plugin/pile_up.cpp
Labels: LGTM

#3001 Upgrade to VS 2019 16.10.0
  base/not_null_test.cpp
  numerics/polynomial.hpp
Labels: LGTM

#3002 Remove references to VS2017
  geometry/pair_test.cpp
  ksp_plugin/pile_up.hpp
Labels: LGTM

#3003 Remove work-arounds for VS 2019 bugs
  geometry/orthogonal_map_body.hpp
  numerics/polynomial_body.hpp
Labels: LGTM

#3005 Use new-style mocks
  integrators/mock_integrators.hpp
  ksp_plugin_test/interface_flight_plan_test.cpp
  ksp_plugin_test/interface_planetarium_test.cpp
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  ksp_plugin_test/mock_celestial.hpp
  ksp_plugin_test/mock_flight_plan.hpp
  ksp_plugin_test/mock_manœuvre.hpp
  ksp_plugin_test/mock_plugin.cpp
  ksp_plugin_test/mock_plugin.hpp
  ksp_plugin_test/mock_renderer.cpp
  ksp_plugin_test/mock_renderer.hpp
  ksp_plugin_test/mock_vessel.hpp
  physics/barycentric_rotating_dynamic_frame_test.cpp
  physics/body_centred_body_direction_dynamic_frame_test.cpp
  physics/body_surface_dynamic_frame_test.cpp
  physics/continuous_trajectory_test.cpp
  physics/mock_continuous_trajectory.hpp
  physics/mock_dynamic_frame.hpp
  physics/mock_ephemeris.hpp
  testing_utilities/actions.hpp
  testing_utilities/testing_utilities.vcxproj
  testing_utilities/testing_utilities.vcxproj.filters
Labels: LGTM

#3006 The great merge of Grassmannian
  base/base.vcxproj
  base/base.vcxproj.filters
  base/recurring_thread.hpp
  base/recurring_thread_body.hpp
  base/recurring_thread_test.cpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/orbit_analyser.cpp
  ksp_plugin/orbit_analyser.hpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/planetarium_test.cpp
  physics/checkpointer.hpp
  physics/checkpointer_body.hpp
  physics/checkpointer_test.cpp
  physics/continuous_trajectory.hpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
Labels: LGTM

#3008 Use designated initializers in more places
  astronomy/lunar_orbit_test.cpp
  astronomy/orbit_analysis_test.cpp
  astronomy/solar_system_dynamics_test.cpp
  numerics/apodization_body.hpp
  numerics/frequency_analysis_test.cpp
  numerics/piecewise_poisson_series_test.cpp
  numerics/poisson_series_basis_body.hpp
  numerics/poisson_series_body.hpp
  numerics/poisson_series_test.cpp
Labels: LGTM

#3007 Use hardware FMA
  astronomy/astronomy.vcxproj
  astronomy/astronomy.vcxproj.filters
  base/macros.hpp
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  geometry/geometry.vcxproj
  geometry/geometry.vcxproj.filters
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  journal/journal.vcxproj
  journal/journal.vcxproj.filters
  ksp_plugin/ksp_plugin.vcxproj
  ksp_plugin/ksp_plugin.vcxproj.filters
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  mathematica/mathematica.vcxproj
  mathematica/mathematica.vcxproj.filters
  numerics/double_precision.hpp
  numerics/double_precision_body.hpp
  numerics/double_precision_test.cpp
  numerics/fma.hpp
  numerics/fma_body.hpp
  numerics/fma_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  physics/physics.vcxproj
  physics/physics.vcxproj.filters
  quantities/elementary_functions.hpp
  quantities/elementary_functions_body.hpp
  quantities/quantities.vcxproj
  quantities/quantities.vcxproj.filters
  testing_utilities/testing_utilities.vcxproj
  testing_utilities/testing_utilities.vcxproj.filters
  tools/tools.vcxproj
  tools/tools.vcxproj.filters
Labels: LGTM

#3009 tools depends on base
  Makefile
Labels: TBR

#3010 -mfma
  Makefile
Labels: TBR

#3012 Revert "Group all the Abseil libraries in the linker command line"
  Makefile
Labels: TBR

#3013 Makefile permutations
  Makefile
Labels: TBR

#3015 Use a group for the absl libraries on Linux
  Makefile
Labels: LGTM

#3016 No recursivity in make
  Makefile
Labels: LGTM

#3017 Normalize the chromium bits in the setup
  Principia.sln
  documentation/Setup Files/chromium.patch
  documentation/Setup Files/chromium_sparse_checkout.txt
  documentation/Setup.md
  rebuild_all_solutions.ps1
Labels: LGTM

#3018 Remove misleading FORCE_INLINE
  numerics/polynomial.hpp
Labels: LGTM
