Repository mockingbirdnest/Principia, pull requests merged in 2021-08, with the labels that each got.

#3080 Do not test Reach’s save in debug
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: LGTM

#3079 Do not attempt to delete the prediction if it was already detached by the caller
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
Labels: LGTM

#3081 Just LOG_IF
  base/macros.hpp
  geometry/orthogonal_map_body.hpp
  integrators/integrators_body.hpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  numerics/polynomial_body.hpp
  physics/continuous_trajectory_body.hpp
  physics/discrete_trajectory_body.hpp
  physics/ephemeris_body.hpp
  physics/rotating_body_body.hpp
Labels: LGTM

#3082 Support for 1.12.2
  ksp_plugin_adapter/gl_lines.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
Labels: LGTM

#3083 Next release is Haar
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3084 Avoid Earth-specific terms for apsides in the Chinese translation
  documentation/bibliography.bib
  documentation/bibliography.pdf
  ksp_plugin_adapter/localization/zh-cn.cfg
Labels: LGTM, localization

#3085 Refactor the ReferenceFrameSelector API
  ksp_plugin_adapter/burn_editor.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/map_node_pool.cs
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM

#3086 Add support for tooltips popping up near the pointer
  ksp_plugin_adapter/window_renderer.cs
Labels: LGTM, ui

#3087 Overhaul the frame selector UI
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/reference_frame_selector.cs
  ksp_plugin_adapter/style.cs
Labels: LGTM, ui

#3088 Merge
  README.md
  base/macros.hpp
  documentation/bibliography.bib
  documentation/bibliography.pdf
  geometry/orthogonal_map_body.hpp
  integrators/integrators_body.hpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_adapter/burn_editor.cs
  ksp_plugin_adapter/gl_lines.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/main_window.cs
  ksp_plugin_adapter/map_node_pool.cs
  ksp_plugin_adapter/reference_frame_selector.cs
  ksp_plugin_adapter/style.cs
  ksp_plugin_adapter/window_renderer.cs
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/saves/3039.proto.hex
  ksp_plugin_test/saves/3072.proto.b64
  numerics/polynomial_body.hpp
  physics/continuous_trajectory_body.hpp
  physics/discrete_trajectory_body.hpp
  physics/ephemeris_body.hpp
  physics/rotating_body_body.hpp
Labels: LGTM

#3092 Translate technical terms in the new frame selector UI
  ksp_plugin_adapter/compatibility_extensions.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/localization_extensions.cs
  ksp_plugin_adapter/orbit_analyser.cs
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM, localization

#3095 Remove the sun lens flare toggle
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3094 Change the Downsampling class to manage a proper data structure and its invariants
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/ephemeris_test.cpp
  physics/forkable_body.hpp
  serialization/physics.proto
Labels: LGTM

#3093 Use celestial-specific terminology
  documentation/bibliography.bib
  documentation/bibliography.pdf
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization/celestial_strings.cfg
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/localization_extensions.cs
  ksp_plugin_adapter/map_node_pool.cs
  ksp_plugin_adapter/orbit_analyser.cs
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM, localization

#3096 Widen the mission duration label
  ksp_plugin_adapter/orbit_analyser.cs
Labels: LGTM

#3097 Add support for downsampling forks
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  physics/forkable_test.cpp
  serialization/physics.proto
Labels: LGTM

#3098 Update zh-cn localization and add strings for the new frame selector
  ksp_plugin_adapter/localization/celestial_strings.cfg
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM

#3091 Fix a compatibility bug
  ksp_plugin/vessel.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
Labels: LGTM

#3099 Fix a compatibility issue with pre-陈景润 saves
  physics/discrete_trajectory_body.hpp
Labels: LGTM

#3090 Write a discrete trajectory checkpoint when closing a non-collapsible segment
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/vessel_test.cpp
  physics/discrete_trajectory_body.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3100 A few improvements to journal replaying
  journal/player.cpp
  journal/player.hpp
  journal/player_test.cpp
  journal/profiles.cpp
Labels: LGTM

#3102 Remove the zfp flag and fix a typo
  physics/discrete_trajectory_body.hpp
Labels: LGTM

#3101 Improve translation malleability
  ksp_plugin_adapter/localization/celestial_strings.cfg
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/localization_extensions.cs
  ksp_plugin_adapter/map_node_pool.cs
  ksp_plugin_adapter/orbit_analyser.cs
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM, localization

#3103 Add support for storing the exact degrees of freedom at some points of a trajectory
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/vessel.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
  physics/ephemeris_test.cpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  physics/forkable_test.cpp
  serialization/physics.proto
Labels: LGTM

#3104 French translations
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/localization/celestial_strings.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
  ksp_plugin_adapter/reference_frame_selector.cs
Labels: LGTM, localization

#3106 Cleanup logging and a new compiler in the pipelines
  base/not_null_test.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/polynomial.hpp
Labels: LGTM

#3105 Allow tracking the root trajectory (not only forks) during serialization
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
  physics/ephemeris_test.cpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  serialization/physics.proto
Labels: LGTM

#3107 Move the code generation to a post-build event of the tools project
  Principia.sln
  ksp_plugin/ksp_plugin.vcxproj
  tools/tools.vcxproj
Labels: LGTM

#3109 Fix a stupid path that causes constant rebuilds
  principia.props
Labels: TBR

#3110 The prehistory is dead, long live the backstory
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/vessel_test.cpp
  physics/checkpointer_body.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3111 Zermelo
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  physics/discrete_trajectory_body.hpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  serialization/ksp_plugin.proto
  serialization/physics.proto
Labels: LGTM

#3108 A diurnal test that reads Butcher’s save
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: LGTM

#3112 Add a function to reanimate one checkpoint
  ksp_plugin/pile_up.cpp
  ksp_plugin/pile_up.hpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/vessel_test.cpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3113 Лидов–古在
  astronomy/astronomy.vcxproj
  astronomy/astronomy.vcxproj.filters
  astronomy/mercury_orbiter.hpp
  astronomy/лидов_古在_test.cpp
  documentation/bibliography.bib
  documentation/bibliography.pdf
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: LGTM

#3117 A new trajectory factory and a test cleanup
  ksp_plugin_test/renderer_test.cpp
  testing_utilities/trajectory_factories.hpp
  testing_utilities/trajectory_factories_body.hpp
  testing_utilities/trajectory_factories_test.cpp
Labels: LGTM

#3116 Use UTF-16 for filenames on Windows only
  astronomy/лидов_古在_test.cpp
  base/macros.hpp
Labels: LGTM

#3118 Add method Reanimate and add thread safety to the Vessel history
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  physics/discrete_trajectory_test.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
Labels: LGTM

#3119 Serialization and deserialization of vessel checkpoints
  ksp_plugin/vessel.cpp
  ksp_plugin_test/vessel_test.cpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3120 Partial serialization of DiscreteTrajectory
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/vessel.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
  physics/ephemeris_test.cpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  serialization/physics.proto
Labels: LGTM

#3121 Unify macros
  astronomy/лидов_古在_test.cpp
  astronomy/молния_orbit_test.cpp
  base/macros.hpp
Labels: LGTM
