Repository mockingbirdnest/Principia, pull requests merged in 2021-07, with the labels that each got.

#3040 Meeus
  astronomy/date_time.hpp
  astronomy/date_time_body.hpp
  astronomy/date_time_test.cpp
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM

#3044 Initialize local variables in constexpr code
  astronomy/date_time_body.hpp
Labels: TBR

#3045 More initialization
  astronomy/date_time_body.hpp
Labels: TBR

#3046 Correct the title of [Wan43]
  Principia.sln
  documentation/bibliography.bib
  documentation/bibliography.pdf
  documentation/cbrt.pdf
Labels: LGTM, documentation

#3042 Make FitHermiteSpline interruptible
  numerics/fit_hermite_spline.hpp
  numerics/fit_hermite_spline_body.hpp
  numerics/fit_hermite_spline_test.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
Labels: LGTM

#3043 Use floating-point numbers, not integers, for a progress indicator in [0, 1]
  ksp_plugin/orbit_analyser.cpp
Labels: LGTM

#3047 Bulletin C 62
  astronomy/eop_c04.generated.h
  astronomy/experimental_eop_c02.generated.h
  astronomy/time_scales_body.hpp
  astronomy/time_scales_test.cpp
Labels: LGTM

#3034 Legible instants
  astronomy/time_scales.hpp
  astronomy/time_scales_body.hpp
  astronomy/time_scales_test.cpp
  geometry/point.hpp
  geometry/point_body.hpp
  numerics/double_precision.hpp
  numerics/double_precision_body.hpp
Labels: LGTM

#3049 NextUp & NextDown
  astronomy/time_scales_body.hpp
  numerics/log_b.hpp
  numerics/log_b_body.hpp
  numerics/next.hpp
  numerics/next_body.hpp
  numerics/next_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/root_finders.hpp
  numerics/root_finders_body.hpp
  numerics/scale_b.hpp
  numerics/scale_b_body.hpp
  numerics/scale_b_test.cpp
  quantities/elementary_functions.hpp
  quantities/elementary_functions_body.hpp
Labels: LGTM

#3048 Legible output for Instant
  Makefile
  astronomy/astronomy.vcxproj
  astronomy/astronomy.vcxproj.filters
  astronomy/time_scales.hpp
  astronomy/time_scales_body.hpp
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  geometry/geometry.vcxproj
  geometry/geometry.vcxproj.filters
  geometry/instant_output.cpp
  geometry/instant_output_test.cpp
  geometry/named_quantities.hpp
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  ksp_plugin/ksp_plugin.vcxproj
  ksp_plugin/ksp_plugin.vcxproj.filters
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  mathematica/mathematica.vcxproj
  mathematica/mathematica.vcxproj.filters
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  physics/physics.vcxproj
  physics/physics.vcxproj.filters
Labels: LGTM

#3053 Oveflow in constexpr arithmetic with clang 8, continued
  base/macros.hpp
  numerics/next_body.hpp
Labels: TBR

#3054 Comparisons are hard
  base/macros.hpp
Labels: TBR

#3055 Strange clang version numbers on macintosh
  base/macros.hpp
Labels: TBR

#3056 Sign error, and it is probably a good idea to #include the macros
  numerics/next_body.hpp
Labels: TBR

#3052 Next release is Grothendieck
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3057 Parentheses
  base/macros.hpp
Labels: TBR

#3058 Restructure a bit the code of the discrete trajectory downsampling
  base/macros.hpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3059 Change downsampling to work for non-root trajectories
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3060 Add version numbers to the C++ DLLs
  base/macros.hpp
  ksp_plugin/ksp_plugin.rc
  ksp_plugin/ksp_plugin.vcxproj
  ksp_plugin/ksp_plugin.vcxproj.filters
  ksp_plugin/resource.h
  serialization/resource.h
  serialization/serialization.rc
  serialization/serialization.vcxproj
  serialization/serialization.vcxproj.filters
Labels: LGTM

#3061 Fix some constants
  documentation/cbrt.pdf
  documentation/cbrt.tex
  documentation/cbrt_latency_misrounding.pdf
Labels: LGTM, documentation

#3063 Add a mechanism to exclude forks at serialization time
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin_test/planetarium_test.cpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_test.cpp
  physics/ephemeris_test.cpp
  physics/forkable.hpp
  physics/forkable_body.hpp
  serialization/physics.proto
Labels: LGTM

#3065 Detect collapsibility changes and fork new segments of the history
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/vessel_test.cpp
  physics/discrete_trajectory_body.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3062 A correctly-rounded cube root.
  documentation/cbrt.pdf
  documentation/cbrt.tex
  numerics/cbrt.cpp
  numerics/cbrt.hpp
  numerics/cbrt_test.cpp
Labels: LGTM

#3066 Don’t carelessly convert fixed-point to floating-point
  numerics/cbrt.cpp
Labels: LGTM

#3067 Emit a message with the compiler version at compile time
  base/version.hpp
Labels: LGTM

#3068 The pipelines are running with MSVC version 192930038
  base/not_null_test.cpp
  numerics/polynomial.hpp
Labels: LGTM

#3069 Confusion between C++ and C#
  Principia C++.slnf
Labels: TBR

#3070 Fix compatibility problems with a pre-Cohen save
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/pre_cohen.proto.hex
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
  physics/ephemeris_body.hpp
Labels: LGTM

#3071 Fix a number of memory management problems
  astronomy/orbit_ground_track_body.hpp
  astronomy/orbital_elements_body.hpp
  base/jthread_body.hpp
  journal/player_test.cpp
  ksp_plugin/vessel.cpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
Labels: LGTM

#3073 Log the compatibility paths
  base/macros.hpp
  geometry/orthogonal_map_body.hpp
  integrators/integrators_body.hpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/part.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/polynomial_body.hpp
  physics/continuous_trajectory_body.hpp
  physics/discrete_trajectory_body.hpp
  physics/ephemeris_body.hpp
  physics/rotating_body_body.hpp
Labels: LGTM

#3076 Test passage in the compatibility paths, add a save by Reach
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/saves/3039.proto.hex
  ksp_plugin_test/saves/3072.proto.b64
Labels: LGTM
