Repository mockingbirdnest/Principia, pull requests merged in 2022-01, with the labels that each got.

#3269 Next release is हरीश चंद्र
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3266 Fix some linguistic issues in the Russian translation
  ksp_plugin_adapter/localization/ru.cfg
Labels: LGTM, localization

#3270 SO(3) is not commutative
  ksp_plugin/frames.hpp
  ksp_plugin/interface_renderer.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin/renderer.cpp
  ksp_plugin/renderer.hpp
  serialization/geometry.proto
Labels: LGTM

#3274 Update the oldest_reanimated_checkpoint_ when the first know checkpoint is created
  journal/player_test.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  physics/ephemeris.hpp
Labels: LGTM

#3275 Bulletin C 63
  astronomy/eop_c04.generated.h
  astronomy/experimental_eop_c02.generated.h
  astronomy/time_scales_body.hpp
  astronomy/time_scales_test.cpp
Labels: LGTM

#3268 Reconstruct the flight plan lazily
  ksp_plugin/interface_flight_plan.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/vessel_test.cpp
Labels: LGTM

#3279 Require Mojave.
  Makefile
  install_deps.sh
Labels: LGTM

#3276 Don’t plot all celestials all the time
  geometry/perspective.hpp
  geometry/perspective_body.hpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/planetarium.cpp
  ksp_plugin/planetarium.hpp
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  serialization/journal.proto
Labels: LGTM

#3282 Do not do multiple checkpoints at the same time
  journal/player_test.cpp
  ksp_plugin/vessel.cpp
Labels: LGTM

#3283 Fix errors found by Clang
  numerics/matrix_computations_body.hpp
  physics/massive_body_body.hpp
Labels: LGTM

#3288 Unrequire Mojave.
  Makefile
  install_deps.sh
Labels: LGTM

#3291 Don't require AVX in cpuid_test.
  base/cpuid_test.cpp
Labels: LGTM

#3287 Add computation of Rayleigh quotient
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/matrix_computations.hpp
  numerics/matrix_computations_body.hpp
  numerics/matrix_computations_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/transposed_view.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
Labels: LGTM

#3292 Zermelo is हरीश चंद्र
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  serialization/ksp_plugin.proto
Labels: LGTM

#3289 Compatibility with latest version of Clang
  Makefile
  base/macros.hpp
  physics/rigid_motion_body.hpp
  quantities/quantities.hpp
Labels: LGTM

#3293 The final merge of Entwurf
  journal/player_test.cpp
  ksp_plugin/interface_external.cpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/pile_up.hpp
  ksp_plugin/plugin.cpp
  ksp_plugin/vessel.cpp
  ksp_plugin/vessel.hpp
  ksp_plugin_adapter/time_span.cs
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/plugin_integration_test.cpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/reanimation test.proto.b64
  ksp_plugin_test/vessel_test.cpp
  physics/checkpointer_body.hpp
  physics/discrete_trajectory.hpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_iterator_body.hpp
  physics/discrete_trajectory_segment_body.hpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
  serialization/ksp_plugin.proto
  testing_utilities/discrete_trajectory_factories_test.cpp
Labels: LGTM

#3294 Move to C++20 and hack the macOS filesystem
  Makefile
  Principia.sln
  base/base.vcxproj
  base/base.vcxproj.filters
  base/macos_filesystem_replacement.hpp
  install_deps.sh
Labels: LGTM

#3295 What do we say to the God of char8_t?
  Makefile
Labels: LGTM

#3296 c++fs seems to be gone
  Makefile
Labels: LGTM

#3297 Stop relying on deprecated operations on enums
  base/macos_filesystem_replacement.hpp
  quantities/dimensions_body.hpp
Labels: LGTM

#3298 Fix benchmark build in Makefile.
  Makefile
Labels: LGTM

#3300 Fix tolerances and a warning with Clang 12
  astronomy/orbital_elements_test.cpp
  ksp_plugin_test/benchmark.cpp
  numerics/frequency_analysis_test.cpp
  numerics/quadrature_test.cpp
  physics/discrete_trajectory_segment_test.cpp
Labels: LGTM

#3299 All hail zygoloid
  base/macros.hpp
  geometry/named_quantities.hpp
  numerics/next_body.hpp
  quantities/quantities.hpp
Labels: LGTM

#3301 Optimizations for DiscreteTrajectory
  benchmarks/discrete_trajectory.cpp
  physics/discrete_trajectory_body.hpp
  physics/discrete_trajectory_iterator.hpp
  physics/discrete_trajectory_iterator_body.hpp
  physics/discrete_trajectory_segment.hpp
  physics/discrete_trajectory_segment_body.hpp
  physics/discrete_trajectory_test.cpp
Labels: LGTM

#3304 Make not_null<foo*> trivially copyable.
  base/not_null.hpp
  base/not_null_body.hpp
  base/not_null_test.cpp
Labels: LGTM

#3303 Plot trajectories using meshes in scaled space
  benchmarks/planetarium_plot_methods.cpp
  journal/profiles.hpp
  ksp_plugin/interface.hpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/planetarium.cpp
  ksp_plugin/planetarium.hpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/gl_lines.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
  ksp_plugin_adapter/plotter.cs
  ksp_plugin_test/interface_planetarium_test.cpp
  ksp_plugin_test/mock_planetarium.hpp
  ksp_plugin_test/mock_plugin.hpp
  ksp_plugin_test/planetarium_test.cpp
  serialization/journal.proto
Labels: LGTM, performance

#3305 Fix the diurnal benchmarks
  benchmark_automation/benchmark_automation.cs
  benchmarks/discrete_trajectory.cpp
Labels: LGTM

#3306 1.12.3
  ksp_plugin_adapter/gl_lines.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
Labels: LGTM

#3308 Fix a few warnings flagged by Clang
  astronomy/лидов_古在_test.cpp
  base/bundle_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp
  ksp_plugin/pile_up.cpp
  ksp_plugin/planetarium.hpp
  ksp_plugin/vessel.cpp
  numerics/matrix_computations_test.cpp
  numerics/poisson_series_basis_test.cpp
  physics/continuous_trajectory_test.cpp
Labels: LGTM

#3307 Added benchmark dependency rules to Makefile.
  Makefile
Labels: LGTM

#3309 Fix a test that was broken by the removal of history()
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: LGTM

#3312 Keep the index count even when the topology is LINES
  ksp_plugin_adapter/plotter.cs
Labels: LGTM

#3313 Put the logic where it does something, and also the right thing
  ksp_plugin_adapter/plotter.cs
Labels: LGTM

#3314 Next release is Hausdorff
  ksp_plugin_adapter/main_window.cs
Labels: LGTM
