Repository mockingbirdnest/Principia, pull requests merged in 2022-05, with the labels that each got.

#3354 Bibliography update
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM, documentation

#3355 A utility for iterating over tuples
  base/base.vcxproj
  base/base.vcxproj.filters
  base/for_all_of.hpp
  base/for_all_of_body.hpp
  base/for_all_of_test.cpp
Labels: LGTM

#3357 Make a test palatable to Clang
  base/for_all_of_test.cpp
Labels: LGTM

#3356 An embedded explicit Runge-Kutta integrator
  integrators/embedded_explicit_runge_kutta_integrator.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  integrators/integrators_body.hpp
  integrators/methods.hpp
  integrators/ordinary_differential_equations.hpp
  integrators/ordinary_differential_equations_body.hpp
  serialization/integrators.proto
  testing_utilities/integration.hpp
  testing_utilities/integration_body.hpp
Labels: LGTM

#3360 Fix an error found by Clang
  integrators/ordinary_differential_equations_body.hpp
Labels: LGTM

#3359 Identifier improvements
  geometry/perspective.hpp
  geometry/perspective_body.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/methods.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
Labels: LGTM

#3361 Some more Visual Studio versions
  base/not_null_test.cpp
  numerics/polynomial.hpp
Labels: LGTM

#3362 Looser tolerances for SolarSystemDynamicsTest
  astronomy/solar_system_dynamics_test.cpp
Labels: TBR

#3363 Try to prevent the tests from stepping on each other
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: TBR

#3364 Fix bad indent in #3363
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: LGTM

#3365 RotationFreeGeometricAccelerationAtRest
  physics/dynamic_frame.hpp
  physics/dynamic_frame_body.hpp
Labels: LGTM

#3367 A class to compute equipotentials and display them in Mathematica
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/ordinary_differential_equations.hpp
  integrators/ordinary_differential_equations_body.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
  integrators/symplectic_runge_kutta_nyström_integrator_body.hpp
  physics/dynamic_frame_body.hpp
  physics/equipotential.hpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
  physics/physics.vcxproj
  physics/physics.vcxproj.filters
Labels: LGTM

#3369 Next release is Hesse
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3370 Change first order ODEs to take an "independent variable" instead of an Instant
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_integrator.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/integrators.hpp
  integrators/integrators_body.hpp
  integrators/ordinary_differential_equations.hpp
  integrators/ordinary_differential_equations_body.hpp
  physics/ephemeris_body.hpp
  physics/equipotential.hpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
  physics/physics.vcxproj.filters
  serialization/integrators.proto
Labels: LGTM
