Repository mockingbirdnest/Principia, pull requests merged in 2023-01, with the labels that each got.

#3495 A benchmark for orbital elements
  benchmarks/apsides.cpp
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  benchmarks/orbital_elements.cpp
  numerics/piecewise_poisson_series_body.hpp
  numerics/poisson_series.hpp
  numerics/poisson_series_body.hpp
  numerics/quadrature.hpp
  numerics/quadrature_body.hpp
Labels: LGTM

#3496 Fix an error found by Clang
  numerics/piecewise_poisson_series_body.hpp
Labels: TBR

#3497 Pass the state to the tolerance function of the adaptive integrators
  benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp
  integrators/integrators.hpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/equipotential.hpp
  physics/equipotential_body.hpp
Labels: LGTM

#3487 Correctly build a series of States to represent equipotential lines
  physics/equipotential.hpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
Labels: LGTM

#3498 Fix the naming of ODEs
  benchmarks/checkpointer_benchmark.cpp
  benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp
  benchmarks/symplectic_runge_kutta_nyström_integrator.cpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_integrator.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp
  integrators/integrators.hpp
  integrators/integrators_body.hpp
  integrators/mock_integrators.hpp
  integrators/ordinary_differential_equations.hpp
  integrators/ordinary_differential_equations_body.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
  integrators/symmetric_linear_multistep_integrator_test.cpp
  integrators/symplectic_partitioned_runge_kutta_integrator.hpp
  integrators/symplectic_partitioned_runge_kutta_integrator_body.hpp
  integrators/symplectic_runge_kutta_nyström_integrator.hpp
  integrators/symplectic_runge_kutta_nyström_integrator_body.hpp
  integrators/symplectic_runge_kutta_nyström_integrator_test.cpp
  ksp_plugin_test/plugin_test.cpp
  mathematica/integrator_plots.cpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/equipotential.hpp
  physics/equipotential_body.hpp
  serialization/integrators.proto
Labels: LGTM

#3500 Change integrators to take the ODE as a template parameter
  astronomy/geodesy_test.cpp
  astronomy/ksp_resonance_test.cpp
  astronomy/ksp_system_test.cpp
  astronomy/lunar_eclipse_test.cpp
  astronomy/lunar_orbit_test.cpp
  astronomy/mercury_perihelion_test.cpp
  astronomy/orbit_analysis_test.cpp
  astronomy/orbital_elements_test.cpp
  astronomy/solar_system_dynamics_test.cpp
  astronomy/standard_product_3_test.cpp
  astronomy/trappist_dynamics_test.cpp
  astronomy/лидов_古在_test.cpp
  astronomy/молния_orbit_test.cpp
  benchmarks/apsides.cpp
  benchmarks/dynamic_frame.cpp
  benchmarks/embedded_explicit_runge_kutta_nyström_integrator.cpp
  benchmarks/ephemeris.cpp
  benchmarks/orbital_elements.cpp
  benchmarks/planetarium_plot_methods.cpp
  benchmarks/symplectic_runge_kutta_nyström_integrator.cpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_integrator.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_test.cpp
  integrators/integrators_body.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
  integrators/symmetric_linear_multistep_integrator_test.cpp
  integrators/symplectic_partitioned_runge_kutta_integrator.hpp
  integrators/symplectic_partitioned_runge_kutta_integrator_body.hpp
  integrators/symplectic_runge_kutta_nyström_integrator.hpp
  integrators/symplectic_runge_kutta_nyström_integrator_body.hpp
  integrators/symplectic_runge_kutta_nyström_integrator_test.cpp
  ksp_plugin/flight_plan.cpp
  ksp_plugin/integrators.cpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/interface_flight_plan_test.cpp
  ksp_plugin_test/orbit_analyser_test.cpp
  ksp_plugin_test/pile_up_test.cpp
  ksp_plugin_test/plugin_integration_test.cpp
  mathematica/integrator_plots.cpp
  mathematica/retrobop_dynamical_stability.cpp
  physics/analytical_series_test.cpp
  physics/apsides_test.cpp
  physics/barycentric_rotating_dynamic_frame_test.cpp
  physics/body_centred_body_direction_dynamic_frame_test.cpp
  physics/body_centred_non_rotating_dynamic_frame_test.cpp
  physics/body_surface_dynamic_frame_test.cpp
  physics/body_test.cpp
  physics/ephemeris_test.cpp
  physics/equipotential_test.cpp
  physics/solar_system_test.cpp
Labels: LGTM

#3502 Fix errors found by Clang
  physics/equipotential.hpp
  physics/equipotential_body.hpp
Labels: TBR

#3504 Update the bibliography
  documentation/bibliography.pdf
Labels: LGTM

#3505 Add class Starter to encapsulate the operations needed to start a linear multistep integrator
  integrators/integrators.hpp
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  integrators/integrators_body.hpp
  integrators/starter.hpp
  integrators/starter_body.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
Labels: LGTM

#3510 Support for 1.12.5
  ksp_plugin_adapter/gl_lines.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/ksp_plugin_adapter.csproj
Labels: LGTM

#3509 Next release is Householder
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3511 Allow a sign after figure spaces
  ksp_plugin_adapter/differential_slider.cs
Labels: LGTM

#3507 Revert "Revert "Add class Starter to encapsulate the operations needed to start a linear multistep integrator""
  integrators/integrators.hpp
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  integrators/integrators_body.hpp
  integrators/starter.hpp
  integrators/starter_body.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
Labels: LGTM

#3508 Fix an error found by Clang
  integrators/symmetric_linear_multistep_integrator_body.hpp
Labels: LGTM

#3513 Fix an error found by Clang
  integrators/symmetric_linear_multistep_integrator_body.hpp
Labels: TBR

#3514 Documentation for the rotating-pulsating frame
  documentation/Rotating Pulsating.pdf
  documentation/Rotating Pulsating.tex
  documentation/basestyle.cls
  documentation/bibliography.bib
  documentation/bibliography.pdf
Labels: LGTM, documentation

#3515 An explicit linear multistep integrator
  documentation/bibliography.bib
  documentation/bibliography.pdf
  integrators/explicit_linear_multistep_integrator.hpp
  integrators/explicit_linear_multistep_integrator_body.hpp
  integrators/explicit_linear_multistep_integrator_test.cpp
  integrators/explicit_runge_kutta_integrator.hpp
  integrators/explicit_runge_kutta_integrator_body.hpp
  integrators/integrators.vcxproj
  integrators/integrators.vcxproj.filters
  integrators/integrators_body.hpp
  integrators/methods.hpp
  integrators/starter.hpp
  integrators/starter_body.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
  serialization/integrators.proto
Labels: LGTM

#3516 More Adams-Bashforth integrators and a better analysis of convergence
  integrators/explicit_linear_multistep_integrator_body.hpp
  integrators/explicit_linear_multistep_integrator_test.cpp
  integrators/integrators_body.hpp
  integrators/methods.hpp
  serialization/integrators.proto
Labels: LGTM

#3517 Improve the benchmark for orbit elements
  benchmarks/orbital_elements.cpp
Labels: LGTM

#3518 Get rid of the obnoxious vectors
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_test.cpp
  integrators/explicit_linear_multistep_integrator_body.hpp
  integrators/explicit_linear_multistep_integrator_test.cpp
  integrators/explicit_runge_kutta_integrator_body.hpp
  integrators/explicit_runge_kutta_integrator_test.cpp
  integrators/ordinary_differential_equations.hpp
  integrators/ordinary_differential_equations_body.hpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
  testing_utilities/integration.hpp
  testing_utilities/integration_body.hpp
Labels: LGTM
