Repository mockingbirdnest/Principia, pull requests merged in 2023-05, with the labels that each got.

#3619 Documentation of the rotational motion of reference frames
  Principia.sln
  documentation/Rotational Motion.pdf
  documentation/Rotational Motion.tex
  documentation/semtex.sty
Labels: LGTM

#3623 Remove dead ends and return DiscreteTrajectory from Equipotential
  physics/equipotential.hpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
Labels: LGTM

#3624 Fix a typo in the explanations related to the triple product
  documentation/Rotational Motion.pdf
  documentation/Rotational Motion.tex
Labels: LGTM

#3616 A correct computation of the angular velocity of a frame
  physics/barycentric_rotating_reference_frame.hpp
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/body_centred_body_direction_reference_frame.hpp
  physics/body_centred_body_direction_reference_frame_body.hpp
  physics/rigid_reference_frame.hpp
  physics/rigid_reference_frame_body.hpp
  physics/rotating_pulsating_reference_frame_test.cpp
  quantities/named_quantities.hpp
Labels: LGTM

#3625 Use the jerk in the computation of rotational motion
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/body_centred_body_direction_reference_frame.hpp
  physics/body_centred_body_direction_reference_frame_body.hpp
  physics/ephemeris.hpp
  physics/ephemeris_body.hpp
  physics/ephemeris_test.cpp
  physics/rotating_pulsating_reference_frame_test.cpp
Labels: LGTM

#3626 Equipotential plotting
  ksp_plugin/geometric_potential_plotter.cpp
  ksp_plugin/geometric_potential_plotter.hpp
  ksp_plugin/interface.cpp
  ksp_plugin/interface_planetarium.cpp
  ksp_plugin/ksp_plugin.vcxproj
  ksp_plugin/ksp_plugin.vcxproj.filters
  ksp_plugin/planetarium.cpp
  ksp_plugin/planetarium.hpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/main_window.cs
  ksp_plugin_adapter/plotter.cs
  ksp_plugin_adapter/reference_frame_selector.cs
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/ksp_plugin_test.vcxproj.filters
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
  serialization/journal.proto
Labels: LGTM

#3627 Draw another equipotential to pinpoint L₄/L₅
  ksp_plugin/geometric_potential_plotter.cpp
  ksp_plugin/geometric_potential_plotter.hpp
Labels: LGTM

#3628 Show lint warnings in the diff
  .github/workflows/lint.yaml
  .github/workflows/pull_request.yml
Labels: LGTM

#3629 Check only changed files when linting a pull request
  .github/workflows/lint.yaml
Labels: LGTM

#3630 NaN resilience in equipotential computing
  journal/player_test.cpp
  ksp_plugin/geometric_potential_plotter.cpp
  physics/geopotential_body.hpp
Labels: LGTM

#3631 Fix the barycentre of the secondary subsystem in the rotating-pulsating frame
  .github/workflows/pull_request.yaml
  Principia.sln
  ksp_plugin/geometric_potential_plotter.cpp
  ksp_plugin/geometric_potential_plotter.hpp
  ksp_plugin/interface.cpp
  ksp_plugin/interface_body.hpp
  ksp_plugin/interface_flight_plan.cpp
  ksp_plugin/interface_renderer.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/burn_editor.cs
  ksp_plugin_adapter/interface.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/map_node_pool.cs
  ksp_plugin_adapter/plotter.cs
  ksp_plugin_adapter/reference_frame_selector.cs
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  physics/barycentric_rotating_reference_frame.hpp
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/barycentric_rotating_reference_frame_test.cpp
  physics/body_centred_body_direction_reference_frame_body.hpp
  physics/rotating_pulsating_reference_frame.hpp
  physics/rotating_pulsating_reference_frame_body.hpp
  serialization/journal.proto
  serialization/physics.proto
Labels: LGTM

#3634 Fix empty range
  physics/barycentric_rotating_reference_frame_body.hpp
Labels: LGTM

#3637 Fix mac build
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/rotating_pulsating_reference_frame_body.hpp
Labels: LGTM

#3638 Fix the mac build some more
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/rotating_pulsating_reference_frame_body.hpp
Labels: TBR

#3639 Pulsate the camera distance in the rotating-pulsating reference frame
  ksp_plugin/interface_renderer.cpp
  ksp_plugin_adapter/planetarium_camera_adjuster.cs
  serialization/journal.proto
Labels: LGTM

#3642 s/трансфер/перелёт/
  ksp_plugin_adapter/localization/ru.cfg
Labels: LGTM, localization

#3641 Use the radius of the secondary system when there are multiple secondaries
  ksp_plugin/geometric_potential_plotter.cpp
Labels: LGTM

#3644 A workflow to build and test Principia
  .github/workflows/build.yaml
  Principia.sln
  find_msbuild.ps1
Labels: LGTM

#3648 Next release is 伊藤
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3650 Do not include changes to ksp_plugin_adapter_stub in the artifact
  .github/workflows/build.yaml
Labels: TBR

#3655 Fix the t_min & t_max of the Tgt *O frame
  physics/body_centred_body_direction_reference_frame_body.hpp
Labels: LGTM

#3656 Support for repeated fields in interchange messages
  ksp_plugin/interface_body.hpp
  ksp_plugin_adapter/boxed.cs
  ksp_plugin_adapter/interface.cs
  ksp_plugin_adapter/repeated_marshaler.cs
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
  tools/journal_proto_processor.hpp
Labels: LGTM

#3652 Update the unity stacktrace parser
  stacktrace_decoder/stacktrace_decoder.cs
Labels: LGTM

#3657 Upgrade to 17.6.0
  base/not_null_test.cpp
  geometry/hilbert.hpp
  geometry/hilbert_body.hpp
  geometry/permutation_test.cpp
  numerics/polynomial.hpp
Labels: TBR

#3658 Try to emit a message slightly more useful than "error 4"
  ksp_plugin_adapter/flight_planner.cs
  ksp_plugin_adapter/interface.cs
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
  ksp_plugin_adapter/localization/ru.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
Labels: LGTM

#3659 On second thoughts, let’s not run RotatingPulsating_GlobalOptimization. ‘Tis a silly test.
  physics/equipotential_test.cpp
Labels: LGTM

#3661 A job that starts our runner VM(s)
  .github/workflows/build.yaml
Labels: LGTM

#3646 Multiple primaries
  ksp_plugin/geometric_potential_plotter.cpp
  ksp_plugin/geometric_potential_plotter.hpp
  ksp_plugin/interface.cpp
  ksp_plugin/interface_body.hpp
  ksp_plugin/interface_flight_plan.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/burn_editor.cs
  ksp_plugin_adapter/interface.cs
  ksp_plugin_adapter/reference_frame_selector.cs
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  physics/barycentric_rotating_reference_frame.hpp
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/barycentric_rotating_reference_frame_test.cpp
  physics/rotating_pulsating_reference_frame.hpp
  physics/rotating_pulsating_reference_frame_body.hpp
  serialization/journal.proto
  serialization/physics.proto
Labels: LGTM, journal-incompatible

#3662 Refactor equipotentials
  ksp_plugin/geometric_potential_plotter.cpp
  ksp_plugin/geometric_potential_plotter.hpp
  physics/equipotential_test.cpp
  physics/lagrange_equipotentials.hpp
  physics/lagrange_equipotentials_body.hpp
  physics/physics.vcxproj
  physics/physics.vcxproj.filters
Labels: LGTM

#3664 typename
  physics/lagrange_equipotentials_body.hpp
Labels: LGTM

#3665 Another typename
  physics/lagrange_equipotentials_body.hpp
Labels: TBR

#3663 Report test failures in the diff
  parallel_test_runner/parallel_test_runner.cs
Labels: LGTM

#3666 Report more errors in the diff
  parallel_test_runner/parallel_test_runner.cs
  physics/lagrange_equipotentials_body.hpp
Labels: LGTM

#3667 Bring back the typename
  physics/lagrange_equipotentials_body.hpp
Labels: TBR
