Repository mockingbirdnest/Principia, pull requests merged in 2023-03, with the labels that each got.

#3540 Fix errors found by Clang
  mathematica/mathematica.hpp
Labels: TBR

#3536 Consider the orbit of the Sun around the Earth
  astronomy/orbital_elements.hpp
  astronomy/orbital_elements_body.hpp
  astronomy/orbital_elements_test.cpp
Labels: LGTM

#3544 No base 32768 on Clang
  testing_utilities/serialization.hpp
Labels: TBR

#3546 Fix inconsistent declarations in algebra testing
  testing_utilities/algebra.hpp
  testing_utilities/algebra_body.hpp
  testing_utilities/algebra_test.cpp
Labels: LGTM

#3545 Gracefully handle trajectories that are not gravitationally bound in OrbitalElements
  astronomy/orbital_elements_body.hpp
  astronomy/orbital_elements_test.cpp
Labels: LGTM

#3550 Renamespace journal
  journal/journal.vcxproj
  journal/journal.vcxproj.filters
  journal/method.hpp
  journal/method_body.hpp
  journal/player.cpp
  journal/player.hpp
  journal/player_body.hpp
  journal/player_test.cpp
  journal/profiles.cpp
  journal/profiles.hpp
  journal/recorder.cpp
  journal/recorder.hpp
  journal/recorder_test.cpp
  renamespacer/Properties/launchSettings.json
  renamespacer/renamespacer.cs
Labels: LGTM

#3551 Try to fix errors found by Clang
  journal/player.hpp
Labels: TBR

#3555 Renamespace plugin test
  ksp_plugin_test/benchmark.cpp
  ksp_plugin_test/celestial_test.cpp
  ksp_plugin_test/equator_relevance_threshold_test.cpp
  ksp_plugin_test/fake_plugin.cpp
  ksp_plugin_test/fake_plugin.hpp
  ksp_plugin_test/flight_plan_test.cpp
  ksp_plugin_test/interface_external_test.cpp
  ksp_plugin_test/interface_flight_plan_test.cpp
  ksp_plugin_test/interface_planetarium_test.cpp
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/manœuvre_test.cpp
  ksp_plugin_test/orbit_analyser_test.cpp
  ksp_plugin_test/part_test.cpp
  ksp_plugin_test/pile_up_test.cpp
  ksp_plugin_test/planetarium_test.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  ksp_plugin_test/plugin_io.cpp
  ksp_plugin_test/plugin_io.hpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/renderer_test.cpp
  ksp_plugin_test/vessel_test.cpp
  renamespace_all_the_things.ps1
Labels: LGTM

#3556 Renamespace mathematica
  astronomy/ksp_system_test.cpp
  astronomy/solar_system_dynamics_test.cpp
  astronomy/trappist_dynamics_test.cpp
  base/macros.hpp
  mathematica/integrator_plots.cpp
  mathematica/integrator_plots.hpp
  mathematica/local_error_analysis.hpp
  mathematica/local_error_analysis_body.hpp
  mathematica/logger.hpp
  mathematica/logger_body.hpp
  mathematica/logger_test.cpp
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  mathematica/mathematica_test.cpp
  mathematica/retrobop_dynamical_stability.cpp
  mathematica/retrobop_dynamical_stability.hpp
  numerics/piecewise_poisson_series.hpp
  numerics/poisson_series.hpp
  numerics/polynomial.hpp
  physics/ephemeris_test.cpp
  renamespace_all_the_things.ps1
Labels: LGTM

#3558 Clang is not my friend
  numerics/polynomial.hpp
Labels: TBR

#3559 More friendship trouble
  numerics/piecewise_poisson_series.hpp
  numerics/poisson_series.hpp
Labels: TBR

#3561 Even more pain with friendship
  physics/discrete_trajectory_iterator.hpp
  physics/discrete_trajectory_segment.hpp
  physics/discrete_trajectory_segment_iterator.hpp
Labels: TBR

#3562 Friend the tests
  physics/discrete_trajectory_iterator.hpp
  physics/discrete_trajectory_segment_iterator.hpp
Labels: TBR

#3560 Renamespace tools
  renamespace_all_the_things.ps1
  tools/generate_configuration.cpp
  tools/generate_configuration.hpp
  tools/generate_kopernicus.cpp
  tools/generate_kopernicus.hpp
  tools/generate_profiles.cpp
  tools/generate_profiles.hpp
  tools/journal_proto_processor.cpp
  tools/journal_proto_processor.hpp
Labels: LGTM

#3565 Next release is Ὑπατία
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3566 Orbit with respect to the sun
  journal/profiles.hpp
  ksp_plugin/interface.hpp
  ksp_plugin/interface_body.hpp
  ksp_plugin/orbit_analyser.cpp
  ksp_plugin_adapter/flight_planner.cs
  ksp_plugin_adapter/orbit_analyser.cs
  serialization/journal.proto
Labels: LGTM

#3568 Restructure OrbitAnalyser::AnalyseOrbit by introducing auxiliary functions
  ksp_plugin/orbit_analyser.cpp
  ksp_plugin/orbit_analyser.hpp
Labels: LGTM

#3567 Heliosynchronous localization
  ksp_plugin_adapter/flight_planner.cs
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
  ksp_plugin_adapter/localization/ru.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/orbit_analyser.cs
Labels: LGTM, localization

#3570 Only push the tag that we are interested in for the release
  make_principia_release.ps1
Labels: LGTM

#3571 A class to represent homothecies
  geometry/geometry.vcxproj
  geometry/geometry.vcxproj.filters
  geometry/homothecy.hpp
  geometry/homothecy_body.hpp
  geometry/homothecy_test.cpp
  geometry/identity.hpp
  geometry/linear_map.hpp
  geometry/orthogonal_map.hpp
  geometry/permutation.hpp
  geometry/rotation.hpp
  geometry/signature.hpp
  serialization/geometry.proto
Labels: LGTM

#3572 Fix errors and warnings found by Clang
  astronomy/orbital_elements_body.hpp
  geometry/homothecy.hpp
  geometry/homothecy_body.hpp
  integrators/embedded_explicit_runge_kutta_integrator_body.hpp
  integrators/explicit_linear_multistep_integrator_test.cpp
  physics/dynamic_frame_test.cpp
  physics/ephemeris_body.hpp
  physics/mock_dynamic_frame.hpp
Labels: LGTM

#3573 Clean up the contract of LinearMap and reify it using CRTP
  geometry/homothecy.hpp
  geometry/identity.hpp
  geometry/identity_body.hpp
  geometry/linear_map.hpp
  geometry/linear_map_body.hpp
  geometry/orthogonal_map.hpp
  geometry/orthogonal_map_body.hpp
  geometry/permutation.hpp
  geometry/permutation_body.hpp
  geometry/rotation.hpp
  geometry/rotation_body.hpp
  geometry/signature.hpp
Labels: LGTM

#3576 Another error found by Clang
  geometry/homothecy_body.hpp
Labels: TBR

#3578 Extract useful utilities from the renamespacer and give it a less specific name
  Principia.sln
  renamespace_all_the_things.ps1
  renamespacer/renamespacer.cs
  sourcerer/Properties/launchSettings.json
  sourcerer/analyser.cs
  sourcerer/filenames.cs
  sourcerer/parser.cs
  sourcerer/renamespacer.cs
  sourcerer/sourcerer.cs
  sourcerer/sourcerer.csproj
Labels: LGTM
