Repository mockingbirdnest/Principia, pull requests merged in 2024-03, with the labels that each got.

#3888 Properly handle a null primary in the orbit analyser
  ksp_plugin_adapter/localization_extensions.cs
Labels: LGTM

#3889 Fix issues with marshaling of classes
  ksp_plugin/interface_flight_plan.cpp
  ksp_plugin_test/interface_flight_plan_test.cpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
  tools/journal_proto_processor.hpp
Labels: LGTM

#3890 Next release is Καραθεοδωρή
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3891 Improve TransposeView by exposing operations for sizing and indexing
  numerics/concepts.hpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/matrix_computations_body.hpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/transposed_view.hpp
  numerics/transposed_view_body.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
Labels: LGTM

#3893 Add support for constructing a matrix from a TransposedView
  ksp_plugin_test/flight_plan_optimizer_test.cpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/transposed_view.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
Labels: LGTM

#3894 Fix errors found by Clang
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_body.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp
  integrators/integrators_body.hpp
  integrators/symmetric_linear_multistep_integrator_body.hpp
  physics/ephemeris.hpp
Labels: TBR

#3895 Migration to Clang 16
  Makefile
  base/version.hpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator.hpp
  integrators/embedded_explicit_runge_kutta_nyström_integrator.hpp
  integrators/integrators.hpp
  integrators/symmetric_linear_multistep_integrator.hpp
  numerics/angle_reduction.hpp
  physics/mechanical_system_test.cpp
  principia.props
Labels: LGTM

#3897 Fix possible dangling references caused by ReturnRef
  ksp_plugin_test/interface_flight_plan_test.cpp
  ksp_plugin_test/interface_planetarium_test.cpp
  ksp_plugin_test/interface_renderer_test.cpp
  ksp_plugin_test/interface_test.cpp
  ksp_plugin_test/pile_up_test.cpp
  ksp_plugin_test/plugin_test.cpp
  ksp_plugin_test/vessel_test.cpp
Labels: LGTM

#3900 Extract BlockView and ColumnView and make them independent from the other arrays
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/matrix_computations_body.hpp
  numerics/matrix_views.hpp
  numerics/matrix_views_body.hpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
Labels: LGTM

#3899 Fix some Clang warnings and silence others
  base/array_body.hpp
  base/cpuid.cpp
  geometry/signature_body.hpp
  numerics/angle_reduction_body.hpp
  numerics/cbrt.cpp
  numerics/fast_sin_cos_2π_test.cpp
  numerics/poisson_series_test.cpp
  numerics/polynomial_in_чебышёв_basis.hpp
  numerics/quadrature_test.cpp
  numerics/root_finders_test.cpp
  numerics/unbounded_arrays_body.hpp
  principia.props
  quantities/elementary_functions_body.hpp
  quantities/parser_body.hpp
Labels: LGTM

#3901 concept quantity
  geometry/grassmann.hpp
  geometry/grassmann_body.hpp
  geometry/hilbert.hpp
  geometry/hilbert_body.hpp
  geometry/point.hpp
  geometry/point_body.hpp
  geometry/point_test.cpp
  geometry/r3_element.hpp
  geometry/r3_element_body.hpp
  geometry/r3x3_matrix.hpp
  geometry/r3x3_matrix_body.hpp
  numerics/double_precision_body.hpp
  numerics/poisson_series_basis_body.hpp
  numerics/polynomial_in_чебышёв_basis.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  quantities/concepts.hpp
  quantities/concepts_test.cpp
  quantities/quantities.vcxproj
  quantities/quantities.vcxproj.filters
  quantities/traits.hpp
Labels: LGTM

#3902 Make the tests for fixed and unbounded arrays consistent
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
Labels: LGTM

#3903 Clean up of operators
  geometry/complexification.hpp
  geometry/complexification_body.hpp
  geometry/grassmann.hpp
  geometry/grassmann_body.hpp
  geometry/pair.hpp
  geometry/pair_body.hpp
  geometry/quaternion.hpp
  geometry/quaternion_body.hpp
  geometry/r3_element.hpp
  geometry/r3x3_matrix.hpp
  geometry/r3x3_matrix_body.hpp
  numerics/double_precision.hpp
  numerics/double_precision_body.hpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/matrix_views.hpp
  numerics/matrix_views_body.hpp
  numerics/piecewise_poisson_series.hpp
  numerics/piecewise_poisson_series_body.hpp
  numerics/poisson_series.hpp
  numerics/poisson_series_body.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
Labels: LGTM, styleguide

#3904 Use defaulted equality whenever possible
  astronomy/standard_product_3.cpp
  astronomy/standard_product_3.hpp
  base/disjoint_sets.hpp
  geometry/complexification.hpp
  geometry/complexification_body.hpp
  geometry/grassmann.hpp
  geometry/grassmann_body.hpp
  geometry/interval.hpp
  geometry/interval_body.hpp
  geometry/linear_map.hpp
  geometry/pair.hpp
  geometry/pair_body.hpp
  geometry/point.hpp
  geometry/point_body.hpp
  geometry/quaternion.hpp
  geometry/quaternion_body.hpp
  geometry/r3x3_matrix.hpp
  geometry/r3x3_matrix_body.hpp
  geometry/rotation.hpp
  geometry/rotation_body.hpp
  geometry/sign.hpp
  geometry/sign_body.hpp
  geometry/symmetric_bilinear_form.hpp
  geometry/symmetric_bilinear_form_body.hpp
  integrators/ordinary_differential_equations.hpp
  numerics/double_precision.hpp
  numerics/double_precision_body.hpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/polynomial.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_чебышёв_basis.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  quantities/quantities.hpp
  quantities/quantities_body.hpp
  testing_utilities/algebra_body.hpp
Labels: LGTM

#3907 Allow specialization of Subset
  base/disjoint_sets.hpp
Labels: TBR

#3905 Use the spaceship operator wherever possible
  astronomy/date_time.hpp
  astronomy/date_time_body.hpp
  astronomy/standard_product_3.cpp
  astronomy/standard_product_3.hpp
  geometry/point.hpp
  geometry/point_body.hpp
  numerics/double_precision.hpp
  numerics/double_precision_body.hpp
  quantities/quantities.hpp
  quantities/quantities_body.hpp
Labels: LGTM

#3908 Update the versions strings in the loader for the newer compilers
  ksp_plugin_adapter/loader.cs
Labels: LGTM

#3911 Make BlockView and ColumnView complete and tested
  numerics/concepts.hpp
  numerics/matrix_views.hpp
  numerics/matrix_views_body.hpp
  numerics/matrix_views_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
Labels: LGTM

#3912 Add some algebraic concepts and remove geometry/traits
  geometry/geometry.vcxproj
  geometry/geometry.vcxproj.filters
  geometry/pair.hpp
  geometry/traits.hpp
  geometry/traits_test.cpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  quantities/concepts.hpp
  quantities/concepts_test.cpp
Labels: LGTM

#3914 Add an actual quantity concept and use it in class Multivector
  base/traits.hpp
  geometry/grassmann.hpp
  geometry/grassmann_body.hpp
  quantities/concepts.hpp
Labels: LGTM

#3916 More algebraic concepts, some tests, and missing operations found by the tests
  geometry/point.hpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
  quantities/concepts.hpp
  quantities/concepts_test.cpp
Labels: LGTM

#3917 Make DegreesOfFreedom an alias of Pair rather than a subclass
  base/base.vcxproj
  base/base.vcxproj.filters
  base/traits_test.cpp
  geometry/pair.hpp
  geometry/pair_body.hpp
  physics/degrees_of_freedom.hpp
  physics/degrees_of_freedom_body.hpp
  physics/physics.vcxproj
  physics/physics.vcxproj.filters
Labels: LGTM

#3919 Use concepts on BarycentreCalculator and drop the specializations
  geometry/barycentre_calculator.hpp
  geometry/barycentre_calculator_body.hpp
  geometry/pair.hpp
  geometry/pair_body.hpp
  geometry/point.hpp
  geometry/point_body.hpp
  numerics/apodization_body.hpp
  numerics/approximation_body.hpp
  numerics/poisson_series_basis_body.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  physics/lagrange_equipotentials_test.cpp
Labels: LGTM

#3918 Change the polynomial evaluators to be specified at the object level and not at the type level
  astronomy/orbit_analysis_test.cpp
  benchmarks/newhall_benchmark.cpp
  benchmarks/polynomial_in_monomial_basis_benchmark.cpp
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  mathematica/mathematica_test.cpp
  numerics/apodization_test.cpp
  numerics/elliptic_functions.cpp
  numerics/elliptic_integrals.cpp
  numerics/fast_sin_cos_2π.cpp
  numerics/frequency_analysis_test.cpp
  numerics/legendre.hpp
  numerics/legendre_body.hpp
  numerics/legendre_test.cpp
  numerics/newhall.hpp
  numerics/newhall_body.hpp
  numerics/newhall_test.cpp
  numerics/piecewise_poisson_series_test.cpp
  numerics/poisson_series.hpp
  numerics/poisson_series_basis_test.cpp
  numerics/poisson_series_body.hpp
  numerics/poisson_series_test.cpp
  numerics/polynomial.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_evaluators.hpp
  numerics/polynomial_evaluators_body.hpp
  numerics/polynomial_evaluators_test.cpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  numerics/polynomial_in_monomial_basis_test.cpp
  numerics/root_finders_test.cpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
  physics/harmonic_damping.hpp
Labels: LGTM

#3922 Fix errors found by Clang
  numerics/newhall_body.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_in_monomial_basis_test.cpp
Labels: TBR

#3920 Get rid of Barycentre of std::pair and simplify its callers
  benchmarks/discrete_trajectory_benchmark.cpp
  geometry/barycentre_calculator.hpp
  geometry/barycentre_calculator_body.hpp
  geometry/barycentre_calculator_test.cpp
  geometry/perspective_body.hpp
  geometry/point_test.cpp
  ksp_plugin/flight_plan_optimizer.cpp
  ksp_plugin_test/flight_plan_optimizer_test.cpp
  ksp_plugin_test/vessel_test.cpp
  mathematica/mathematica_body.hpp
  numerics/apodization_body.hpp
  numerics/approximation_body.hpp
  numerics/nearest_neighbour_body.hpp
  numerics/newhall_body.hpp
  numerics/poisson_series_basis_body.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  numerics/root_finders_body.hpp
  physics/apsides_body.hpp
  physics/barycentric_rotating_reference_frame_body.hpp
  physics/barycentric_rotating_reference_frame_test.cpp
  physics/body_centred_body_direction_reference_frame_test.cpp
  physics/ephemeris_test.cpp
  physics/equipotential_body.hpp
  physics/equipotential_test.cpp
  physics/lagrange_equipotentials_body.hpp
  physics/lagrange_equipotentials_test.cpp
Labels: LGTM

#3921 Serialization and deserialization of evaluators
  numerics/polynomial.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_evaluators.hpp
  numerics/polynomial_evaluators_body.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  numerics/polynomial_in_monomial_basis_test.cpp
  physics/continuous_trajectory_body.hpp
  physics/continuous_trajectory_test.cpp
  serialization/numerics.proto
Labels: LGTM

#3923 A single-parameter overload of Barycentre.
  geometry/barycentre_calculator.hpp
  geometry/barycentre_calculator_body.hpp
  geometry/point_test.cpp
  ksp_plugin_test/flight_plan_optimizer_test.cpp
  mathematica/mathematica_body.hpp
  numerics/apodization_body.hpp
  numerics/approximation_body.hpp
  numerics/nearest_neighbour_body.hpp
  numerics/newhall_body.hpp
  numerics/poisson_series_basis_body.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  numerics/root_finders_body.hpp
  physics/ephemeris_test.cpp
Labels: LGTM

#3924 Remove the evaluator from the Poisson series
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  mathematica/mathematica_test.cpp
  numerics/apodization.cpp
  numerics/apodization.hpp
  numerics/apodization_test.cpp
  numerics/frequency_analysis.hpp
  numerics/frequency_analysis_body.hpp
  numerics/frequency_analysis_test.cpp
  numerics/numerics.vcxproj
  numerics/piecewise_poisson_series.hpp
  numerics/piecewise_poisson_series_body.hpp
  numerics/piecewise_poisson_series_test.cpp
  numerics/poisson_series.hpp
  numerics/poisson_series_basis_test.cpp
  numerics/poisson_series_body.hpp
  numerics/poisson_series_test.cpp
Labels: LGTM

#3927 Remove fast_sin_cos_2π
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  benchmarks/fast_sin_cos_2π_benchmark.cpp
  numerics/fast_sin_cos_2π.cpp
  numerics/fast_sin_cos_2π.hpp
  numerics/fast_sin_cos_2π_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  shared/numerics.vcxitems
Labels: LGTM

#3926 No need for a Barycentre for containers.
  geometry/barycentre_calculator.hpp
  geometry/barycentre_calculator_body.hpp
  geometry/point_test.cpp
  numerics/nearest_neighbour_body.hpp
  physics/degrees_of_freedom_test.cpp
Labels: LGTM

#3930 Improve the benchmark for polynomial evaluation
  benchmarks/polynomial_in_monomial_basis_benchmark.cpp
Labels: LGTM

#3928 Remove macros that work around ancient MSVC bugs
  base/macros.hpp
  numerics/piecewise_poisson_series.hpp
  numerics/piecewise_poisson_series_body.hpp
  numerics/poisson_series.hpp
  numerics/poisson_series_body.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
Labels: LGTM

#3933 Link geometry into tools, as it needs the instant output operator
  Makefile
Labels: LGTM

#3931 Test Reach’s save without FMA
  base/macros.hpp
  ksp_plugin_test/ksp_plugin_test.vcxproj
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/fma.hpp
Labels: LGTM

#3932 Optimize the polynomial evaluation
  base/macros.hpp
  numerics/polynomial.hpp
  numerics/polynomial_evaluators_body.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  numerics/polynomial_in_чебышёв_basis.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
Labels: LGTM

#3934 Fix some benchmark command lines
  benchmarks/encoder_benchmark.cpp
  benchmarks/polynomial_in_monomial_basis_benchmark.cpp
  benchmarks/polynomial_in_чебышёв_basis_benchmark.cpp
Labels: LGTM

#3935 Use the start_runners action in the build workflow
  .github/workflows/build.yaml
Labels: LGTM

#3936 An action to keep runners alive
  .github/workflows/keep_alive.yaml
Labels: LGTM

#3937 Bad indent
  .github/workflows/keep_alive.yaml
Labels: TBR

#3938 Run the keep_alive worflow at noon every four days
  .github/workflows/keep_alive.yaml
Labels: LGTM

#3940 Fix a bug in the deserialization of integrators
  base/macros.hpp
  geometry/r3_element_body.hpp
  geometry/r3x3_matrix_body.hpp
  integrators/integrators_body.hpp
  ksp_plugin/interface_body.hpp
  ksp_plugin_test/pile_up_test.cpp
  numerics/global_optimization_body.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  physics/body_body.hpp
  physics/euler_solver_body.hpp
  physics/geopotential_body.hpp
  physics/hierarchical_system_body.hpp
  physics/massive_body_body.hpp
  physics/oblate_body_body.hpp
  physics/solar_system_body.hpp
  quantities/parser_body.hpp
  testing_utilities/solar_system_factory_body.hpp
  tools/journal_proto_processor.cpp
Labels: LGTM

#3941 Remove a TODO, it seems that we can now evaluate high-degree Legendre polynomials
  integrators/embedded_explicit_generalized_runge_kutta_nyström_integrator_test.cpp
Labels: LGTM

#3939 benchmark_automation: Verify we ran all benchmarks once and drop the CSV output
  benchmark_automation/benchmark_automation.cs
Labels: LGTM

#3944 Try to fix the clang build
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/fma.hpp
Labels: TBR

#3943 Log CPUID information on startup
  base/cpuid.cpp
  base/cpuid.hpp
  base/cpuid_test.cpp
  geometry/grassmann_test.cpp
  geometry/point_test.cpp
  ksp_plugin/interface.cpp
  numerics/cbrt_test.cpp
  numerics/fma.hpp
  numerics/fma_test.cpp
  quantities/elementary_functions_test.cpp
Labels: LGTM

#3947 Our C++ is too modern for clang
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: TBR

#3948 Fix the mac build
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: TBR

#3949 Fix #3947
  ksp_plugin_test/plugin_compatibility_test.cpp
Labels: TBR

#3950 fp-contract=off
  Makefile
Labels: TBR

#3945 Fix a few TODOs
  numerics/fit_hermite_spline.hpp
  numerics/fit_hermite_spline_body.hpp
  numerics/fit_hermite_spline_test.cpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/hermite3.hpp
  numerics/hermite3_body.hpp
  numerics/hermite3_test.cpp
  numerics/poisson_series.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
  physics/apsides_body.hpp
  physics/discrete_trajectory_segment.hpp
  physics/discrete_trajectory_segment_body.hpp
Labels: LGTM

#3951 Make not_null constexpr
  base/not_null.hpp
  base/not_null_body.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
Labels: LGTM

#3952 Fix a misconfigured benchmark
  benchmarks/rigid_reference_frame_benchmark.cpp
Labels: LGTM

#3946 Down with benchmark_min_time
  benchmarks/approximation_benchmark.cpp
  benchmarks/apsides_benchmark.cpp
  benchmarks/elliptic_functions_benchmark.cpp
  benchmarks/elliptic_integrals_benchmark.cpp
  benchmarks/embedded_explicit_runge_kutta_nyström_integrator_benchmark.cpp
  benchmarks/encoder_benchmark.cpp
  benchmarks/geopotential_benchmark.cpp
  benchmarks/newhall_benchmark.cpp
  benchmarks/orbital_elements_benchmark.cpp
  benchmarks/symplectic_runge_kutta_nyström_integrator_benchmark.cpp
  benchmarks/thread_pool_benchmark.cpp
Labels: LGTM

#3953 First attempt at fixing tests on macOS and Ubuntu
  astronomy/orbit_analysis_test.cpp
  astronomy/orbital_elements_test.cpp
  astronomy/лидов_古在_test.cpp
  base/cpuid_test.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/approximation_test.cpp
  numerics/poisson_series_test.cpp
  numerics/quadrature_test.cpp
  physics/euler_solver_test.cpp
Labels: LGTM

#3954 Initialize the flags in the same place as the flag registry
  base/cpuid.cpp
  base/cpuid.hpp
  base/cpuid_test.cpp
  geometry/grassmann_test.cpp
  geometry/point_test.cpp
  numerics/cbrt_test.cpp
  numerics/fma.hpp
  numerics/fma_test.cpp
  quantities/elementary_functions_test.cpp
Labels: LGTM

#3955 Revert spurious macro changes from #3931
  base/macros.hpp
Labels: LGTM
