Repository mockingbirdnest/Principia, pull requests merged in 2024-02, with the labels that each got.

#3860 Add a streaming computation of interpolants, and use it to stop once the first collision has been found
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  physics/apsides_body.hpp
Labels: LGTM, verified

#3862 Handle larger fold expressions in Clang
  Makefile
Labels: TBR

#3863 Code cleanup based on Clang warnings
  integrators/explicit_runge_kutta_integrator_body.hpp
  integrators/explicit_runge_kutta_integrator_test.cpp
  ksp_plugin_test/plugin_compatibility_test.cpp
  numerics/finite_difference_test.cpp
  numerics/matrix_computations_body.hpp
  physics/apsides_body.hpp
  physics/discrete_trajectory_iterator_test.cpp
  physics/rigid_reference_frame_body.hpp
Labels: LGTM

#3864 Move PolynomialInMonomialBasis to its own file
  astronomy/lunar_orbit_test.cpp
  astronomy/orbit_analysis_test.cpp
  benchmarks/benchmarks.vcxproj
  benchmarks/perspective_benchmark.cpp
  benchmarks/planetarium_benchmark.cpp
  benchmarks/polynomial_in_monomial_basis_benchmark.cpp
  geometry/perspective_test.cpp
  ksp_plugin_test/flight_plan_optimizer_test.cpp
  ksp_plugin_test/interface_external_test.cpp
  ksp_plugin_test/part_test.cpp
  ksp_plugin_test/planetarium_test.cpp
  ksp_plugin_test/vessel_test.cpp
  mathematica/mathematica.hpp
  mathematica/mathematica_test.cpp
  numerics/elliptic_functions.cpp
  numerics/elliptic_integrals.cpp
  numerics/fast_sin_cos_2π.cpp
  numerics/gradient_descent_test.cpp
  numerics/legendre.hpp
  numerics/newhall.hpp
  numerics/newhall_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/poisson_series.hpp
  numerics/polynomial.hpp
  numerics/polynomial_body.hpp
  numerics/polynomial_evaluators.hpp
  numerics/polynomial_in_monomial_basis.hpp
  numerics/polynomial_in_monomial_basis_body.hpp
  numerics/polynomial_in_monomial_basis_test.cpp
  numerics/root_finders_test.cpp
  physics/apsides_test.cpp
  physics/continuous_trajectory_test.cpp
  physics/harmonic_damping.hpp
  physics/rigid_reference_frame_test.cpp
  physics/rotating_pulsating_reference_frame_test.cpp
  physics/similar_motion_test.cpp
  sourcerer/Properties/launchSettings.json
  sourcerer/filenames.cs
  sourcerer/include_what_you_using.cs
Labels: LGTM

#3867 More tolerance changes in the diurnal test
  ksp_plugin_test/flight_plan_optimizer_test.cpp
Labels: LGTM

#3870 Improvements to PolynomialInЧебышёвBasis
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  mathematica/mathematica_test.cpp
  numerics/polynomial_in_чебышёв_basis.hpp
  numerics/polynomial_in_чебышёв_basis_body.hpp
  serialization/numerics.proto
Labels: LGTM

#3874 Fix errors found by Clang
  numerics/polynomial_in_чебышёв_basis_body.hpp
Labels: TBR

#3875 Support for Visual Studio 17.8.6
  base/not_null_test.cpp
  geometry/hilbert.hpp
  geometry/hilbert_body.hpp
  numerics/gradient_descent_body.hpp
  numerics/polynomial_in_чебышёв_basis.hpp
Labels: LGTM

#3876 Don't remove a guidance node that is for another vessel
  ksp_plugin_adapter/ksp_plugin_adapter.cs
Labels: LGTM

#3871 Replace ЧебышёвSeries with PolynomialInЧебышёвBasis in the approximation code
  benchmarks/approximation_benchmark.cpp
  find_msbuild.ps1
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/polynomial_in_чебышёв_basis_body.hpp
  numerics/quadrature_body.hpp
  numerics/чебышёв_lobatto.hpp
  numerics/чебышёв_lobatto_body.hpp
  physics/apsides_body.hpp
Labels: LGTM

#3877 Fix an error found by Clang
  numerics/approximation_body.hpp
Labels: TBR

#3881 Change the generator to produce a marshaler when exchanging a message that has is_class
  ksp_plugin/interface_flight_plan.cpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
  tools/journal_proto_processor.hpp
Labels: LGTM

#3882 Fix locking in PushPullCallback
  base/push_pull_callback.hpp
  base/push_pull_callback_body.hpp
  journal/player_test.cpp
Labels: LGTM

#3880 Make it build on clang 16+
  astronomy/orbit_recurrence_body.hpp
  astronomy/orbital_elements_body.hpp
  numerics/elliptic_integrals.cpp
Labels: LGTM

#3883 Change the Newhall approximation to use the new PolynomialInЧебышёвBasis
  benchmarks/approximation_benchmark.cpp
  benchmarks/newhall_benchmark.cpp
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/newhall.hpp
  numerics/newhall_body.hpp
  numerics/newhall_test.cpp
  numerics/numerics.vcxproj.filters
Labels: LGTM

#3885 Remove ЧебышёвSeries
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  benchmarks/чебышёв_series_benchmark.cpp
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  mathematica/mathematica_test.cpp
  numerics/numerics.vcxproj
  numerics/numerics.vcxproj.filters
  numerics/polynomial_in_чебышёв_basis_body.hpp
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
  physics/continuous_trajectory_body.hpp
Labels: LGTM
