Repository mockingbirdnest/Principia, pull requests merged in 2024-01, with the labels that each got.

#3830 Frobenius companion matrix in the Чебышёв basis
  numerics/combinatorics.hpp
  numerics/combinatorics_body.hpp
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
Labels: LGTM

#3832 Compute the terrain altitude at the right place to determine whether the periapsis is underground
  ksp_plugin_adapter/map_node_pool.cs
Labels: LGTM

#3833 Hessenberg decomposition of a matrix
  geometry/r3x3_matrix_test.cpp
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/matrix_computations.hpp
  numerics/matrix_computations_body.hpp
  numerics/matrix_computations_test.cpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
  testing_utilities/almost_equals_body.hpp
Labels: LGTM

#3834 Use a deduction guide to fix errors found by Clang
  numerics/matrix_computations_body.hpp
  numerics/transposed_view.hpp
Labels: TBR

#3835 Use CONSTEXPR_DCHECK in constexpr functions
  numerics/matrix_computations_body.hpp
Labels: TBR

#3838 Fix a dangling reference
  numerics/matrix_computations_body.hpp
Labels: TBR

#3840 Computation of the real Schur decomposition of a matrix
  numerics/matrix_computations.hpp
  numerics/matrix_computations_body.hpp
  numerics/matrix_computations_test.cpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
Labels: LGTM

#3841 Fix an error found by Clang
  numerics/matrix_computations_body.hpp
Labels: TBR

#3842 Next release is 掛谷
  ksp_plugin_adapter/main_window.cs
Labels: LGTM

#3843 Clean up the arrays code
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/fixed_arrays_test.cpp
  numerics/matrix_computations_body.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
  numerics/unbounded_arrays_test.cpp
Labels: LGTM

#3844 Change the vector and matrix classes to reexport their Scalar parameter
  numerics/fixed_arrays.hpp
  numerics/fixed_arrays_body.hpp
  numerics/matrix_computations_body.hpp
  numerics/unbounded_arrays.hpp
  numerics/unbounded_arrays_body.hpp
Labels: LGTM

#3845 A function to compute the time intervals where a trajectory can collide with a celestial
  geometry/interval.hpp
  geometry/interval_body.hpp
  physics/apsides.hpp
  physics/apsides_body.hpp
  physics/apsides_test.cpp
  testing_utilities/matchers.hpp
Labels: LGTM

#3846 Some improvements to the computations of collisions
  mathematica/mathematica.hpp
  mathematica/mathematica_body.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  numerics/matrix_computations_body.hpp
  numerics/matrix_computations_test.cpp
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
Labels: LGTM

#3847 A function to compute the roots of a Чебышёв series
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
Labels: LGTM

#3848 A function to compute the first collision between a vessel and a celestial
  numerics/чебышёв_series_body.hpp
  physics/apsides.hpp
  physics/apsides_body.hpp
  physics/apsides_test.cpp
Labels: LGTM

#3849 Improvements to Чебышёв polynomial approximants
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  physics/apsides_body.hpp
Labels: LGTM

#3850 Adaptive Чебышёв polynomial interpolant with interval subdivision
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
Labels: LGTM

#3851 Detection of zero-free Чебышёв series
  documentation/bibliography.bib
  documentation/bibliography.pdf
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
Labels: LGTM

#3852 Integrate collision detection with the game
  journal/profiles.hpp
  ksp_plugin/interface.hpp
  ksp_plugin/interface_body.hpp
  ksp_plugin/interface_collision.cpp
  ksp_plugin/plugin.cpp
  ksp_plugin/plugin.hpp
  ksp_plugin_adapter/disposable.cs
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/map_node_pool.cs
  numerics/approximation_body.hpp
  numerics/matrix_computations_body.hpp
  numerics/чебышёв_series_test.cpp
  physics/apsides_body.hpp
  physics/apsides_test.cpp
  physics/trajectory.hpp
  serialization/journal.proto
  tools/journal_proto_processor.cpp
Labels: LGTM, journal-incompatible

#3853 A bunch of cleanups related to collisions
  ksp_plugin/plugin.cpp
  physics/apsides.hpp
  physics/apsides_body.hpp
  physics/apsides_test.cpp
Labels: LGTM

#3854 Change the zero-free test of the Чебышёв series to take an error estimate
  numerics/чебышёв_series.hpp
  numerics/чебышёв_series_body.hpp
  numerics/чебышёв_series_test.cpp
Labels: LGTM

#3856 Avoid subdividing the zero-free intervals
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  physics/apsides_body.hpp
Labels: LGTM

#3857 A benchmark for AdaptiveЧебышёвPolynomialInterpolant and some optimizations
  benchmarks/approximation_benchmark.cpp
  benchmarks/benchmarks.vcxproj
  benchmarks/benchmarks.vcxproj.filters
  numerics/approximation.hpp
  numerics/approximation_body.hpp
  numerics/approximation_test.cpp
  numerics/fixed_arrays_body.hpp
  numerics/matrix_computations_test.cpp
  physics/apsides_body.hpp
Labels: LGTM

#3858 Add captions to the impact marker
  ksp_plugin_adapter/localization/en-us.cfg
  ksp_plugin_adapter/localization/fr-fr.cfg
  ksp_plugin_adapter/localization/ru.cfg
  ksp_plugin_adapter/localization/zh-cn.cfg
  ksp_plugin_adapter/map_node_pool.cs
Labels: LGTM

#3859 Support for collisions in the flight plan
  ksp_plugin_adapter/ksp_plugin_adapter.cs
  ksp_plugin_adapter/map_node_pool.cs
Labels: LGTM
